import { State, TypeofToken } from '@/lexer/automata.types'
import { ReservedWords } from '@/lexer/lexer.types'
import {
  Action,
  ActionTable,
  FollowTable,
  GotoTable,
  NonTerminals
} from './parser.types'

const ACTION_TABLE: ActionTable = new Map([
  [
    0,
    new Map<TypeofToken | ReservedWords, Action>([
      ['inicio', { action: 'SHIFT', identifier: 2 }],
      ['varinicio', { action: 'ERROR', identifier: 1 }],
      ['varfim', { action: 'ERROR', identifier: 1 }],
      ['PT_V', { action: 'ERROR', identifier: 1 }],
      ['ID', { action: 'ERROR', identifier: 1 }],
      ['VIR', { action: 'ERROR', identifier: 1 }],
      ['inteiro', { action: 'ERROR', identifier: 1 }],
      ['real', { action: 'ERROR', identifier: 1 }],
      ['literal', { action: 'ERROR', identifier: 1 }],
      ['leia', { action: 'ERROR', identifier: 1 }],
      ['escreva', { action: 'ERROR', identifier: 1 }],
      ['LIT', { action: 'ERROR', identifier: 1 }],
      ['NUM', { action: 'ERROR', identifier: 1 }],
      ['ATR', { action: 'ERROR', identifier: 1 }],
      ['OPA', { action: 'ERROR', identifier: 1 }],
      ['se', { action: 'ERROR', identifier: 1 }],
      ['AB_P', { action: 'ERROR', identifier: 1 }],
      ['FC_P', { action: 'ERROR', identifier: 1 }],
      ['entao', { action: 'ERROR', identifier: 1 }],
      ['OPR', { action: 'ERROR', identifier: 1 }],
      ['fimse', { action: 'ERROR', identifier: 1 }],
      ['fim', { action: 'ERROR', identifier: 1 }],
      ['EOF', { action: 'ERROR', identifier: 1 }]
    ])
  ],
  [
    1,
    new Map<TypeofToken | ReservedWords, Action>([
      ['inicio', { action: 'ERROR', identifier: 2 }],
      ['varinicio', { action: 'ERROR', identifier: 2 }],
      ['varfim', { action: 'ERROR', identifier: 2 }],
      ['PT_V', { action: 'ERROR', identifier: 2 }],
      ['ID', { action: 'ERROR', identifier: 2 }],
      ['VIR', { action: 'ERROR', identifier: 2 }],
      ['inteiro', { action: 'ERROR', identifier: 2 }],
      ['real', { action: 'ERROR', identifier: 2 }],
      ['literal', { action: 'ERROR', identifier: 2 }],
      ['leia', { action: 'ERROR', identifier: 2 }],
      ['escreva', { action: 'ERROR', identifier: 2 }],
      ['LIT', { action: 'ERROR', identifier: 2 }],
      ['NUM', { action: 'ERROR', identifier: 2 }],
      ['ATR', { action: 'ERROR', identifier: 2 }],
      ['OPA', { action: 'ERROR', identifier: 2 }],
      ['se', { action: 'ERROR', identifier: 2 }],
      ['AB_P', { action: 'ERROR', identifier: 2 }],
      ['FC_P', { action: 'ERROR', identifier: 2 }],
      ['entao', { action: 'ERROR', identifier: 2 }],
      ['OPR', { action: 'ERROR', identifier: 2 }],
      ['fimse', { action: 'ERROR', identifier: 2 }],
      ['fim', { action: 'ERROR', identifier: 2 }],
      ['EOF', { action: 'ACCEPT', identifier: 1 }]
    ])
  ],
  [
    2,
    new Map<TypeofToken | ReservedWords, Action>([
      ['inicio', { action: 'ERROR', identifier: 3 }],
      ['varinicio', { action: 'SHIFT', identifier: 4 }],
      ['varfim', { action: 'ERROR', identifier: 4 }],
      ['PT_V', { action: 'ERROR', identifier: 4 }],
      ['ID', { action: 'ERROR', identifier: 4 }],
      ['VIR', { action: 'ERROR', identifier: 4 }],
      ['inteiro', { action: 'ERROR', identifier: 4 }],
      ['real', { action: 'ERROR', identifier: 4 }],
      ['literal', { action: 'ERROR', identifier: 4 }],
      ['leia', { action: 'ERROR', identifier: 4 }],
      ['escreva', { action: 'ERROR', identifier: 4 }],
      ['LIT', { action: 'ERROR', identifier: 4 }],
      ['NUM', { action: 'ERROR', identifier: 4 }],
      ['ATR', { action: 'ERROR', identifier: 4 }],
      ['OPA', { action: 'ERROR', identifier: 4 }],
      ['se', { action: 'ERROR', identifier: 4 }],
      ['AB_P', { action: 'ERROR', identifier: 4 }],
      ['FC_P', { action: 'ERROR', identifier: 4 }],
      ['entao', { action: 'ERROR', identifier: 4 }],
      ['OPR', { action: 'ERROR', identifier: 4 }],
      ['fimse', { action: 'ERROR', identifier: 4 }],
      ['fim', { action: 'ERROR', identifier: 4 }],
      ['EOF', { action: 'ERROR', identifier: 4 }]
    ])
  ],
  [
    3,
    new Map<TypeofToken | ReservedWords, Action>([
      ['inicio', { action: 'ERROR', identifier: 4 }],
      ['varinicio', { action: 'ERROR', identifier: 4 }],
      ['varfim', { action: 'ERROR', identifier: 4 }],
      ['PT_V', { action: 'ERROR', identifier: 4 }],
      ['ID', { action: 'SHIFT', identifier: 12 }],
      ['VIR', { action: 'ERROR', identifier: 4 }],
      ['inteiro', { action: 'ERROR', identifier: 4 }],
      ['real', { action: 'ERROR', identifier: 4 }],
      ['literal', { action: 'ERROR', identifier: 4 }],
      ['leia', { action: 'SHIFT', identifier: 10 }],
      ['escreva', { action: 'SHIFT', identifier: 11 }],
      ['LIT', { action: 'ERROR', identifier: 4 }],
      ['NUM', { action: 'ERROR', identifier: 4 }],
      ['ATR', { action: 'ERROR', identifier: 4 }],
      ['OPA', { action: 'ERROR', identifier: 4 }],
      ['se', { action: 'SHIFT', identifier: 14 }],
      ['AB_P', { action: 'ERROR', identifier: 4 }],
      ['FC_P', { action: 'ERROR', identifier: 4 }],
      ['entao', { action: 'ERROR', identifier: 4 }],
      ['OPR', { action: 'ERROR', identifier: 4 }],
      ['fimse', { action: 'ERROR', identifier: 4 }],
      ['fim', { action: 'SHIFT', identifier: 9 }],
      ['EOF', { action: 'ERROR', identifier: 4 }]
    ])
  ],
  [
    4,
    new Map<TypeofToken | ReservedWords, Action>([
      ['inicio', { action: 'ERROR', identifier: 4 }],
      ['varinicio', { action: 'ERROR', identifier: 4 }],
      ['varfim', { action: 'SHIFT', identifier: 17 }],
      ['PT_V', { action: 'ERROR', identifier: 4 }],
      ['ID', { action: 'ERROR', identifier: 4 }],
      ['VIR', { action: 'ERROR', identifier: 4 }],
      ['inteiro', { action: 'SHIFT', identifier: 19 }],
      ['real', { action: 'SHIFT', identifier: 20 }],
      ['literal', { action: 'SHIFT', identifier: 21 }],
      ['leia', { action: 'ERROR', identifier: 4 }],
      ['escreva', { action: 'ERROR', identifier: 4 }],
      ['LIT', { action: 'ERROR', identifier: 4 }],
      ['NUM', { action: 'ERROR', identifier: 4 }],
      ['ATR', { action: 'ERROR', identifier: 4 }],
      ['OPA', { action: 'ERROR', identifier: 4 }],
      ['se', { action: 'ERROR', identifier: 4 }],
      ['AB_P', { action: 'ERROR', identifier: 4 }],
      ['FC_P', { action: 'ERROR', identifier: 4 }],
      ['entao', { action: 'ERROR', identifier: 4 }],
      ['OPR', { action: 'ERROR', identifier: 4 }],
      ['fimse', { action: 'ERROR', identifier: 4 }],
      ['fim', { action: 'ERROR', identifier: 4 }],
      ['EOF', { action: 'ERROR', identifier: 4 }]
    ])
  ],
  [
    5,
    new Map<TypeofToken | ReservedWords, Action>([
      ['inicio', { action: 'ERROR', identifier: 2 }],
      ['varinicio', { action: 'ERROR', identifier: 2 }],
      ['varfim', { action: 'ERROR', identifier: 2 }],
      ['PT_V', { action: 'ERROR', identifier: 2 }],
      ['ID', { action: 'ERROR', identifier: 2 }],
      ['VIR', { action: 'ERROR', identifier: 2 }],
      ['inteiro', { action: 'ERROR', identifier: 2 }],
      ['real', { action: 'ERROR', identifier: 2 }],
      ['literal', { action: 'ERROR', identifier: 2 }],
      ['leia', { action: 'ERROR', identifier: 2 }],
      ['escreva', { action: 'ERROR', identifier: 2 }],
      ['LIT', { action: 'ERROR', identifier: 2 }],
      ['NUM', { action: 'ERROR', identifier: 2 }],
      ['ATR', { action: 'ERROR', identifier: 2 }],
      ['OPA', { action: 'ERROR', identifier: 2 }],
      ['se', { action: 'ERROR', identifier: 2 }],
      ['AB_P', { action: 'ERROR', identifier: 2 }],
      ['FC_P', { action: 'ERROR', identifier: 2 }],
      ['entao', { action: 'ERROR', identifier: 2 }],
      ['OPR', { action: 'ERROR', identifier: 2 }],
      ['fimse', { action: 'ERROR', identifier: 2 }],
      ['fim', { action: 'ERROR', identifier: 2 }],
      ['EOF', { action: 'REDUCE', identifier: 1 }]
    ])
  ],
  [
    6,
    new Map<TypeofToken | ReservedWords, Action>([
      ['inicio', { action: 'ERROR', identifier: 4 }],
      ['varinicio', { action: 'ERROR', identifier: 4 }],
      ['varfim', { action: 'ERROR', identifier: 4 }],
      ['PT_V', { action: 'ERROR', identifier: 4 }],
      ['ID', { action: 'SHIFT', identifier: 12 }],
      ['VIR', { action: 'ERROR', identifier: 4 }],
      ['inteiro', { action: 'ERROR', identifier: 4 }],
      ['real', { action: 'ERROR', identifier: 4 }],
      ['literal', { action: 'ERROR', identifier: 4 }],
      ['leia', { action: 'SHIFT', identifier: 10 }],
      ['escreva', { action: 'SHIFT', identifier: 11 }],
      ['LIT', { action: 'ERROR', identifier: 4 }],
      ['NUM', { action: 'ERROR', identifier: 4 }],
      ['ATR', { action: 'ERROR', identifier: 4 }],
      ['OPA', { action: 'ERROR', identifier: 4 }],
      ['se', { action: 'SHIFT', identifier: 14 }],
      ['AB_P', { action: 'ERROR', identifier: 4 }],
      ['FC_P', { action: 'ERROR', identifier: 4 }],
      ['entao', { action: 'ERROR', identifier: 4 }],
      ['OPR', { action: 'ERROR', identifier: 4 }],
      ['fimse', { action: 'ERROR', identifier: 4 }],
      ['fim', { action: 'SHIFT', identifier: 9 }],
      ['EOF', { action: 'ERROR', identifier: 4 }]
    ])
  ],
  [
    7,
    new Map<TypeofToken | ReservedWords, Action>([
      ['inicio', { action: 'ERROR', identifier: 4 }],
      ['varinicio', { action: 'ERROR', identifier: 4 }],
      ['varfim', { action: 'ERROR', identifier: 4 }],
      ['PT_V', { action: 'ERROR', identifier: 4 }],
      ['ID', { action: 'SHIFT', identifier: 12 }],
      ['VIR', { action: 'ERROR', identifier: 4 }],
      ['inteiro', { action: 'ERROR', identifier: 4 }],
      ['real', { action: 'ERROR', identifier: 4 }],
      ['literal', { action: 'ERROR', identifier: 4 }],
      ['leia', { action: 'SHIFT', identifier: 10 }],
      ['escreva', { action: 'SHIFT', identifier: 11 }],
      ['LIT', { action: 'ERROR', identifier: 4 }],
      ['NUM', { action: 'ERROR', identifier: 4 }],
      ['ATR', { action: 'ERROR', identifier: 4 }],
      ['OPA', { action: 'ERROR', identifier: 4 }],
      ['se', { action: 'SHIFT', identifier: 14 }],
      ['AB_P', { action: 'ERROR', identifier: 4 }],
      ['FC_P', { action: 'ERROR', identifier: 4 }],
      ['entao', { action: 'ERROR', identifier: 4 }],
      ['OPR', { action: 'ERROR', identifier: 4 }],
      ['fimse', { action: 'ERROR', identifier: 4 }],
      ['fim', { action: 'SHIFT', identifier: 9 }],
      ['EOF', { action: 'ERROR', identifier: 4 }]
    ])
  ],
  [
    8,
    new Map<TypeofToken | ReservedWords, Action>([
      ['inicio', { action: 'ERROR', identifier: 4 }],
      ['varinicio', { action: 'ERROR', identifier: 4 }],
      ['varfim', { action: 'ERROR', identifier: 4 }],
      ['PT_V', { action: 'ERROR', identifier: 4 }],
      ['ID', { action: 'SHIFT', identifier: 12 }],
      ['VIR', { action: 'ERROR', identifier: 4 }],
      ['inteiro', { action: 'ERROR', identifier: 4 }],
      ['real', { action: 'ERROR', identifier: 4 }],
      ['literal', { action: 'ERROR', identifier: 4 }],
      ['leia', { action: 'SHIFT', identifier: 10 }],
      ['escreva', { action: 'SHIFT', identifier: 11 }],
      ['LIT', { action: 'ERROR', identifier: 4 }],
      ['NUM', { action: 'ERROR', identifier: 4 }],
      ['ATR', { action: 'ERROR', identifier: 4 }],
      ['OPA', { action: 'ERROR', identifier: 4 }],
      ['se', { action: 'SHIFT', identifier: 14 }],
      ['AB_P', { action: 'ERROR', identifier: 4 }],
      ['FC_P', { action: 'ERROR', identifier: 4 }],
      ['entao', { action: 'ERROR', identifier: 4 }],
      ['OPR', { action: 'ERROR', identifier: 4 }],
      ['fimse', { action: 'ERROR', identifier: 4 }],
      ['fim', { action: 'SHIFT', identifier: 9 }],
      ['EOF', { action: 'ERROR', identifier: 4 }]
    ])
  ],
  [
    9,
    new Map<TypeofToken | ReservedWords, Action>([
      ['inicio', { action: 'ERROR', identifier: 2 }],
      ['varinicio', { action: 'ERROR', identifier: 2 }],
      ['varfim', { action: 'ERROR', identifier: 2 }],
      ['PT_V', { action: 'ERROR', identifier: 2 }],
      ['ID', { action: 'ERROR', identifier: 2 }],
      ['VIR', { action: 'ERROR', identifier: 2 }],
      ['inteiro', { action: 'ERROR', identifier: 2 }],
      ['real', { action: 'ERROR', identifier: 2 }],
      ['literal', { action: 'ERROR', identifier: 2 }],
      ['leia', { action: 'ERROR', identifier: 2 }],
      ['escreva', { action: 'ERROR', identifier: 2 }],
      ['LIT', { action: 'ERROR', identifier: 2 }],
      ['NUM', { action: 'ERROR', identifier: 2 }],
      ['ATR', { action: 'ERROR', identifier: 2 }],
      ['OPA', { action: 'ERROR', identifier: 2 }],
      ['se', { action: 'ERROR', identifier: 2 }],
      ['AB_P', { action: 'ERROR', identifier: 2 }],
      ['FC_P', { action: 'ERROR', identifier: 2 }],
      ['entao', { action: 'ERROR', identifier: 2 }],
      ['OPR', { action: 'ERROR', identifier: 2 }],
      ['fimse', { action: 'ERROR', identifier: 2 }],
      ['fim', { action: 'ERROR', identifier: 2 }],
      ['EOF', { action: 'REDUCE', identifier: 31 }]
    ])
  ],
  [
    10,
    new Map<TypeofToken | ReservedWords, Action>([
      ['inicio', { action: 'ERROR', identifier: 5 }],
      ['varinicio', { action: 'ERROR', identifier: 5 }],
      ['varfim', { action: 'ERROR', identifier: 5 }],
      ['PT_V', { action: 'ERROR', identifier: 5 }],
      ['ID', { action: 'SHIFT', identifier: 25 }],
      ['VIR', { action: 'ERROR', identifier: 5 }],
      ['inteiro', { action: 'ERROR', identifier: 5 }],
      ['real', { action: 'ERROR', identifier: 5 }],
      ['literal', { action: 'ERROR', identifier: 5 }],
      ['leia', { action: 'ERROR', identifier: 5 }],
      ['escreva', { action: 'ERROR', identifier: 5 }],
      ['LIT', { action: 'ERROR', identifier: 5 }],
      ['NUM', { action: 'ERROR', identifier: 5 }],
      ['ATR', { action: 'ERROR', identifier: 5 }],
      ['OPA', { action: 'ERROR', identifier: 5 }],
      ['se', { action: 'ERROR', identifier: 5 }],
      ['AB_P', { action: 'ERROR', identifier: 5 }],
      ['FC_P', { action: 'ERROR', identifier: 5 }],
      ['entao', { action: 'ERROR', identifier: 5 }],
      ['OPR', { action: 'ERROR', identifier: 5 }],
      ['fimse', { action: 'ERROR', identifier: 5 }],
      ['fim', { action: 'ERROR', identifier: 5 }],
      ['EOF', { action: 'ERROR', identifier: 5 }]
    ])
  ],
  [
    11,
    new Map<TypeofToken | ReservedWords, Action>([
      ['inicio', { action: 'ERROR', identifier: 4 }],
      ['varinicio', { action: 'ERROR', identifier: 4 }],
      ['varfim', { action: 'ERROR', identifier: 4 }],
      ['PT_V', { action: 'ERROR', identifier: 4 }],
      ['ID', { action: 'SHIFT', identifier: 29 }],
      ['VIR', { action: 'ERROR', identifier: 4 }],
      ['inteiro', { action: 'ERROR', identifier: 4 }],
      ['real', { action: 'ERROR', identifier: 4 }],
      ['literal', { action: 'ERROR', identifier: 4 }],
      ['leia', { action: 'ERROR', identifier: 4 }],
      ['escreva', { action: 'ERROR', identifier: 4 }],
      ['LIT', { action: 'SHIFT', identifier: 27 }],
      ['NUM', { action: 'SHIFT', identifier: 28 }],
      ['ATR', { action: 'ERROR', identifier: 4 }],
      ['OPA', { action: 'ERROR', identifier: 4 }],
      ['se', { action: 'ERROR', identifier: 4 }],
      ['AB_P', { action: 'ERROR', identifier: 4 }],
      ['FC_P', { action: 'ERROR', identifier: 4 }],
      ['entao', { action: 'ERROR', identifier: 4 }],
      ['OPR', { action: 'ERROR', identifier: 4 }],
      ['fimse', { action: 'ERROR', identifier: 4 }],
      ['fim', { action: 'ERROR', identifier: 4 }],
      ['EOF', { action: 'ERROR', identifier: 4 }]
    ])
  ],
  [
    12,
    new Map<TypeofToken | ReservedWords, Action>([
      ['inicio', { action: 'ERROR', identifier: 6 }],
      ['varinicio', { action: 'ERROR', identifier: 6 }],
      ['varfim', { action: 'ERROR', identifier: 6 }],
      ['PT_V', { action: 'ERROR', identifier: 6 }],
      ['ID', { action: 'ERROR', identifier: 6 }],
      ['VIR', { action: 'ERROR', identifier: 6 }],
      ['inteiro', { action: 'ERROR', identifier: 6 }],
      ['real', { action: 'ERROR', identifier: 6 }],
      ['literal', { action: 'ERROR', identifier: 6 }],
      ['leia', { action: 'ERROR', identifier: 6 }],
      ['escreva', { action: 'ERROR', identifier: 6 }],
      ['LIT', { action: 'ERROR', identifier: 6 }],
      ['NUM', { action: 'ERROR', identifier: 6 }],
      ['ATR', { action: 'SHIFT', identifier: 30 }],
      ['OPA', { action: 'ERROR', identifier: 6 }],
      ['se', { action: 'ERROR', identifier: 6 }],
      ['AB_P', { action: 'ERROR', identifier: 6 }],
      ['FC_P', { action: 'ERROR', identifier: 6 }],
      ['entao', { action: 'ERROR', identifier: 6 }],
      ['OPR', { action: 'ERROR', identifier: 6 }],
      ['fimse', { action: 'ERROR', identifier: 6 }],
      ['fim', { action: 'ERROR', identifier: 6 }],
      ['EOF', { action: 'ERROR', identifier: 6 }]
    ])
  ],
  [
    13,
    new Map<TypeofToken | ReservedWords, Action>([
      ['inicio', { action: 'ERROR', identifier: 4 }],
      ['varinicio', { action: 'ERROR', identifier: 4 }],
      ['varfim', { action: 'ERROR', identifier: 4 }],
      ['PT_V', { action: 'ERROR', identifier: 4 }],
      ['ID', { action: 'SHIFT', identifier: 12 }],
      ['VIR', { action: 'ERROR', identifier: 4 }],
      ['inteiro', { action: 'ERROR', identifier: 4 }],
      ['real', { action: 'ERROR', identifier: 4 }],
      ['literal', { action: 'ERROR', identifier: 4 }],
      ['leia', { action: 'SHIFT', identifier: 10 }],
      ['escreva', { action: 'SHIFT', identifier: 11 }],
      ['LIT', { action: 'ERROR', identifier: 4 }],
      ['NUM', { action: 'ERROR', identifier: 4 }],
      ['ATR', { action: 'ERROR', identifier: 4 }],
      ['OPA', { action: 'ERROR', identifier: 4 }],
      ['se', { action: 'SHIFT', identifier: 14 }],
      ['AB_P', { action: 'ERROR', identifier: 4 }],
      ['FC_P', { action: 'ERROR', identifier: 4 }],
      ['entao', { action: 'ERROR', identifier: 4 }],
      ['OPR', { action: 'ERROR', identifier: 4 }],
      ['fimse', { action: 'SHIFT', identifier: 35 }],
      ['fim', { action: 'ERROR', identifier: 4 }],
      ['EOF', { action: 'ERROR', identifier: 4 }]
    ])
  ],
  [
    14,
    new Map<TypeofToken | ReservedWords, Action>([
      ['inicio', { action: 'ERROR', identifier: 7 }],
      ['varinicio', { action: 'ERROR', identifier: 7 }],
      ['varfim', { action: 'ERROR', identifier: 7 }],
      ['PT_V', { action: 'ERROR', identifier: 7 }],
      ['ID', { action: 'ERROR', identifier: 7 }],
      ['VIR', { action: 'ERROR', identifier: 7 }],
      ['inteiro', { action: 'ERROR', identifier: 7 }],
      ['real', { action: 'ERROR', identifier: 7 }],
      ['literal', { action: 'ERROR', identifier: 7 }],
      ['leia', { action: 'ERROR', identifier: 7 }],
      ['escreva', { action: 'ERROR', identifier: 7 }],
      ['LIT', { action: 'ERROR', identifier: 7 }],
      ['NUM', { action: 'ERROR', identifier: 7 }],
      ['ATR', { action: 'ERROR', identifier: 7 }],
      ['OPA', { action: 'ERROR', identifier: 7 }],
      ['se', { action: 'ERROR', identifier: 7 }],
      ['AB_P', { action: 'SHIFT', identifier: 36 }],
      ['FC_P', { action: 'ERROR', identifier: 7 }],
      ['entao', { action: 'ERROR', identifier: 7 }],
      ['OPR', { action: 'ERROR', identifier: 7 }],
      ['fimse', { action: 'ERROR', identifier: 7 }],
      ['fim', { action: 'ERROR', identifier: 7 }],
      ['EOF', { action: 'ERROR', identifier: 7 }]
    ])
  ],
  [
    15,
    new Map<TypeofToken | ReservedWords, Action>([
      ['inicio', { action: 'ERROR', identifier: 9 }],
      ['varinicio', { action: 'ERROR', identifier: 9 }],
      ['varfim', { action: 'ERROR', identifier: 9 }],
      ['PT_V', { action: 'ERROR', identifier: 9 }],
      ['ID', { action: 'REDUCE', identifier: 2 }],
      ['VIR', { action: 'ERROR', identifier: 9 }],
      ['inteiro', { action: 'ERROR', identifier: 9 }],
      ['real', { action: 'ERROR', identifier: 9 }],
      ['literal', { action: 'ERROR', identifier: 9 }],
      ['leia', { action: 'REDUCE', identifier: 2 }],
      ['escreva', { action: 'REDUCE', identifier: 2 }],
      ['LIT', { action: 'ERROR', identifier: 9 }],
      ['NUM', { action: 'ERROR', identifier: 9 }],
      ['ATR', { action: 'ERROR', identifier: 9 }],
      ['OPA', { action: 'ERROR', identifier: 9 }],
      ['se', { action: 'REDUCE', identifier: 2 }],
      ['AB_P', { action: 'ERROR', identifier: 9 }],
      ['FC_P', { action: 'ERROR', identifier: 9 }],
      ['entao', { action: 'ERROR', identifier: 9 }],
      ['OPR', { action: 'ERROR', identifier: 9 }],
      ['fimse', { action: 'ERROR', identifier: 9 }],
      ['fim', { action: 'REDUCE', identifier: 2 }],
      ['EOF', { action: 'ERROR', identifier: 9 }]
    ])
  ],
  [
    16,
    new Map<TypeofToken | ReservedWords, Action>([
      ['inicio', { action: 'ERROR', identifier: 4 }],
      ['varinicio', { action: 'ERROR', identifier: 4 }],
      ['varfim', { action: 'SHIFT', identifier: 17 }],
      ['PT_V', { action: 'ERROR', identifier: 4 }],
      ['ID', { action: 'ERROR', identifier: 4 }],
      ['VIR', { action: 'ERROR', identifier: 4 }],
      ['inteiro', { action: 'SHIFT', identifier: 19 }],
      ['real', { action: 'SHIFT', identifier: 20 }],
      ['literal', { action: 'SHIFT', identifier: 21 }],
      ['leia', { action: 'ERROR', identifier: 4 }],
      ['escreva', { action: 'ERROR', identifier: 4 }],
      ['LIT', { action: 'ERROR', identifier: 4 }],
      ['NUM', { action: 'ERROR', identifier: 4 }],
      ['ATR', { action: 'ERROR', identifier: 4 }],
      ['OPA', { action: 'ERROR', identifier: 4 }],
      ['se', { action: 'ERROR', identifier: 4 }],
      ['AB_P', { action: 'ERROR', identifier: 4 }],
      ['FC_P', { action: 'ERROR', identifier: 4 }],
      ['entao', { action: 'ERROR', identifier: 4 }],
      ['OPR', { action: 'ERROR', identifier: 4 }],
      ['fimse', { action: 'ERROR', identifier: 4 }],
      ['fim', { action: 'ERROR', identifier: 4 }],
      ['EOF', { action: 'ERROR', identifier: 4 }]
    ])
  ],
  [
    17,
    new Map<TypeofToken | ReservedWords, Action>([
      ['inicio', { action: 'ERROR', identifier: 4 }],
      ['varinicio', { action: 'ERROR', identifier: 4 }],
      ['varfim', { action: 'ERROR', identifier: 4 }],
      ['PT_V', { action: 'SHIFT', identifier: 38 }],
      ['ID', { action: 'ERROR', identifier: 4 }],
      ['VIR', { action: 'ERROR', identifier: 8 }],
      ['inteiro', { action: 'ERROR', identifier: 4 }],
      ['real', { action: 'ERROR', identifier: 4 }],
      ['literal', { action: 'ERROR', identifier: 4 }],
      ['leia', { action: 'ERROR', identifier: 4 }],
      ['escreva', { action: 'ERROR', identifier: 4 }],
      ['LIT', { action: 'ERROR', identifier: 4 }],
      ['NUM', { action: 'ERROR', identifier: 4 }],
      ['ATR', { action: 'ERROR', identifier: 4 }],
      ['OPA', { action: 'ERROR', identifier: 4 }],
      ['se', { action: 'ERROR', identifier: 4 }],
      ['AB_P', { action: 'ERROR', identifier: 4 }],
      ['FC_P', { action: 'ERROR', identifier: 4 }],
      ['entao', { action: 'ERROR', identifier: 4 }],
      ['OPR', { action: 'ERROR', identifier: 4 }],
      ['fimse', { action: 'ERROR', identifier: 4 }],
      ['fim', { action: 'ERROR', identifier: 4 }],
      ['EOF', { action: 'ERROR', identifier: 4 }]
    ])
  ],
  [
    18,
    new Map<TypeofToken | ReservedWords, Action>([
      ['inicio', { action: 'ERROR', identifier: 4 }],
      ['varinicio', { action: 'ERROR', identifier: 4 }],
      ['varfim', { action: 'ERROR', identifier: 4 }],
      ['PT_V', { action: 'ERROR', identifier: 4 }],
      ['ID', { action: 'SHIFT', identifier: 40 }],
      ['VIR', { action: 'ERROR', identifier: 4 }],
      ['inteiro', { action: 'ERROR', identifier: 4 }],
      ['real', { action: 'ERROR', identifier: 4 }],
      ['literal', { action: 'ERROR', identifier: 4 }],
      ['leia', { action: 'ERROR', identifier: 4 }],
      ['escreva', { action: 'ERROR', identifier: 4 }],
      ['LIT', { action: 'ERROR', identifier: 4 }],
      ['NUM', { action: 'ERROR', identifier: 4 }],
      ['ATR', { action: 'ERROR', identifier: 4 }],
      ['OPA', { action: 'ERROR', identifier: 4 }],
      ['se', { action: 'ERROR', identifier: 4 }],
      ['AB_P', { action: 'ERROR', identifier: 4 }],
      ['FC_P', { action: 'ERROR', identifier: 4 }],
      ['entao', { action: 'ERROR', identifier: 4 }],
      ['OPR', { action: 'ERROR', identifier: 4 }],
      ['fimse', { action: 'ERROR', identifier: 4 }],
      ['fim', { action: 'ERROR', identifier: 4 }],
      ['EOF', { action: 'ERROR', identifier: 4 }]
    ])
  ],
  [
    19,
    new Map<TypeofToken | ReservedWords, Action>([
      ['inicio', { action: 'ERROR', identifier: 9 }],
      ['varinicio', { action: 'ERROR', identifier: 9 }],
      ['varfim', { action: 'ERROR', identifier: 9 }],
      ['PT_V', { action: 'ERROR', identifier: 9 }],
      ['ID', { action: 'REDUCE', identifier: 8 }],
      ['VIR', { action: 'ERROR', identifier: 9 }],
      ['inteiro', { action: 'ERROR', identifier: 9 }],
      ['real', { action: 'ERROR', identifier: 9 }],
      ['literal', { action: 'ERROR', identifier: 9 }],
      ['leia', { action: 'ERROR', identifier: 9 }],
      ['escreva', { action: 'ERROR', identifier: 9 }],
      ['LIT', { action: 'ERROR', identifier: 9 }],
      ['NUM', { action: 'ERROR', identifier: 9 }],
      ['ATR', { action: 'ERROR', identifier: 9 }],
      ['OPA', { action: 'ERROR', identifier: 9 }],
      ['se', { action: 'ERROR', identifier: 9 }],
      ['AB_P', { action: 'ERROR', identifier: 9 }],
      ['FC_P', { action: 'ERROR', identifier: 9 }],
      ['entao', { action: 'ERROR', identifier: 9 }],
      ['OPR', { action: 'ERROR', identifier: 9 }],
      ['fimse', { action: 'ERROR', identifier: 9 }],
      ['fim', { action: 'ERROR', identifier: 9 }],
      ['EOF', { action: 'ERROR', identifier: 9 }]
    ])
  ],
  [
    20,
    new Map<TypeofToken | ReservedWords, Action>([
      ['inicio', { action: 'ERROR', identifier: 9 }],
      ['varinicio', { action: 'ERROR', identifier: 9 }],
      ['varfim', { action: 'ERROR', identifier: 9 }],
      ['PT_V', { action: 'ERROR', identifier: 9 }],
      ['ID', { action: 'REDUCE', identifier: 9 }],
      ['VIR', { action: 'ERROR', identifier: 9 }],
      ['inteiro', { action: 'ERROR', identifier: 9 }],
      ['real', { action: 'ERROR', identifier: 9 }],
      ['literal', { action: 'ERROR', identifier: 9 }],
      ['leia', { action: 'ERROR', identifier: 9 }],
      ['escreva', { action: 'ERROR', identifier: 9 }],
      ['LIT', { action: 'ERROR', identifier: 9 }],
      ['NUM', { action: 'ERROR', identifier: 9 }],
      ['ATR', { action: 'ERROR', identifier: 9 }],
      ['OPA', { action: 'ERROR', identifier: 9 }],
      ['se', { action: 'ERROR', identifier: 9 }],
      ['AB_P', { action: 'ERROR', identifier: 9 }],
      ['FC_P', { action: 'ERROR', identifier: 9 }],
      ['entao', { action: 'ERROR', identifier: 9 }],
      ['OPR', { action: 'ERROR', identifier: 9 }],
      ['fimse', { action: 'ERROR', identifier: 9 }],
      ['fim', { action: 'ERROR', identifier: 9 }],
      ['EOF', { action: 'ERROR', identifier: 9 }]
    ])
  ],
  [
    21,
    new Map<TypeofToken | ReservedWords, Action>([
      ['inicio', { action: 'ERROR', identifier: 9 }],
      ['varinicio', { action: 'ERROR', identifier: 9 }],
      ['varfim', { action: 'ERROR', identifier: 9 }],
      ['PT_V', { action: 'ERROR', identifier: 9 }],
      ['ID', { action: 'REDUCE', identifier: 10 }],
      ['VIR', { action: 'ERROR', identifier: 9 }],
      ['inteiro', { action: 'ERROR', identifier: 9 }],
      ['real', { action: 'ERROR', identifier: 9 }],
      ['literal', { action: 'ERROR', identifier: 9 }],
      ['leia', { action: 'ERROR', identifier: 9 }],
      ['escreva', { action: 'ERROR', identifier: 9 }],
      ['LIT', { action: 'ERROR', identifier: 9 }],
      ['NUM', { action: 'ERROR', identifier: 9 }],
      ['ATR', { action: 'ERROR', identifier: 9 }],
      ['OPA', { action: 'ERROR', identifier: 9 }],
      ['se', { action: 'ERROR', identifier: 9 }],
      ['AB_P', { action: 'ERROR', identifier: 9 }],
      ['FC_P', { action: 'ERROR', identifier: 9 }],
      ['entao', { action: 'ERROR', identifier: 9 }],
      ['OPR', { action: 'ERROR', identifier: 9 }],
      ['fimse', { action: 'ERROR', identifier: 9 }],
      ['fim', { action: 'ERROR', identifier: 9 }],
      ['EOF', { action: 'ERROR', identifier: 9 }]
    ])
  ],
  [
    22,
    new Map<TypeofToken | ReservedWords, Action>([
      ['inicio', { action: 'ERROR', identifier: 2 }],
      ['varinicio', { action: 'ERROR', identifier: 2 }],
      ['varfim', { action: 'ERROR', identifier: 2 }],
      ['PT_V', { action: 'ERROR', identifier: 2 }],
      ['ID', { action: 'ERROR', identifier: 2 }],
      ['VIR', { action: 'ERROR', identifier: 2 }],
      ['inteiro', { action: 'ERROR', identifier: 2 }],
      ['real', { action: 'ERROR', identifier: 2 }],
      ['literal', { action: 'ERROR', identifier: 2 }],
      ['leia', { action: 'ERROR', identifier: 2 }],
      ['escreva', { action: 'ERROR', identifier: 2 }],
      ['LIT', { action: 'ERROR', identifier: 2 }],
      ['NUM', { action: 'ERROR', identifier: 2 }],
      ['ATR', { action: 'ERROR', identifier: 2 }],
      ['OPA', { action: 'ERROR', identifier: 2 }],
      ['se', { action: 'ERROR', identifier: 2 }],
      ['AB_P', { action: 'ERROR', identifier: 2 }],
      ['FC_P', { action: 'ERROR', identifier: 2 }],
      ['entao', { action: 'ERROR', identifier: 2 }],
      ['OPR', { action: 'ERROR', identifier: 2 }],
      ['fimse', { action: 'ERROR', identifier: 2 }],
      ['fim', { action: 'ERROR', identifier: 2 }],
      ['EOF', { action: 'REDUCE', identifier: 11 }]
    ])
  ],
  [
    23,
    new Map<TypeofToken | ReservedWords, Action>([
      ['inicio', { action: 'ERROR', identifier: 2 }],
      ['varinicio', { action: 'ERROR', identifier: 2 }],
      ['varfim', { action: 'ERROR', identifier: 2 }],
      ['PT_V', { action: 'ERROR', identifier: 2 }],
      ['ID', { action: 'ERROR', identifier: 2 }],
      ['VIR', { action: 'ERROR', identifier: 2 }],
      ['inteiro', { action: 'ERROR', identifier: 2 }],
      ['real', { action: 'ERROR', identifier: 2 }],
      ['literal', { action: 'ERROR', identifier: 2 }],
      ['leia', { action: 'ERROR', identifier: 2 }],
      ['escreva', { action: 'ERROR', identifier: 2 }],
      ['LIT', { action: 'ERROR', identifier: 2 }],
      ['NUM', { action: 'ERROR', identifier: 2 }],
      ['ATR', { action: 'ERROR', identifier: 2 }],
      ['OPA', { action: 'ERROR', identifier: 2 }],
      ['se', { action: 'ERROR', identifier: 2 }],
      ['AB_P', { action: 'ERROR', identifier: 2 }],
      ['FC_P', { action: 'ERROR', identifier: 2 }],
      ['entao', { action: 'ERROR', identifier: 2 }],
      ['OPR', { action: 'ERROR', identifier: 2 }],
      ['fimse', { action: 'ERROR', identifier: 2 }],
      ['fim', { action: 'ERROR', identifier: 2 }],
      ['EOF', { action: 'REDUCE', identifier: 17 }]
    ])
  ],
  [
    24,
    new Map<TypeofToken | ReservedWords, Action>([
      ['inicio', { action: 'ERROR', identifier: 2 }],
      ['varinicio', { action: 'ERROR', identifier: 2 }],
      ['varfim', { action: 'ERROR', identifier: 2 }],
      ['PT_V', { action: 'ERROR', identifier: 2 }],
      ['ID', { action: 'ERROR', identifier: 2 }],
      ['VIR', { action: 'ERROR', identifier: 2 }],
      ['inteiro', { action: 'ERROR', identifier: 2 }],
      ['real', { action: 'ERROR', identifier: 2 }],
      ['literal', { action: 'ERROR', identifier: 2 }],
      ['leia', { action: 'ERROR', identifier: 2 }],
      ['escreva', { action: 'ERROR', identifier: 2 }],
      ['LIT', { action: 'ERROR', identifier: 2 }],
      ['NUM', { action: 'ERROR', identifier: 2 }],
      ['ATR', { action: 'ERROR', identifier: 2 }],
      ['OPA', { action: 'ERROR', identifier: 2 }],
      ['se', { action: 'ERROR', identifier: 2 }],
      ['AB_P', { action: 'ERROR', identifier: 2 }],
      ['FC_P', { action: 'ERROR', identifier: 2 }],
      ['entao', { action: 'ERROR', identifier: 2 }],
      ['OPR', { action: 'ERROR', identifier: 2 }],
      ['fimse', { action: 'ERROR', identifier: 2 }],
      ['fim', { action: 'ERROR', identifier: 2 }],
      ['EOF', { action: 'REDUCE', identifier: 23 }]
    ])
  ],
  [
    25,
    new Map<TypeofToken | ReservedWords, Action>([
      ['inicio', { action: 'ERROR', identifier: 4 }],
      ['varinicio', { action: 'ERROR', identifier: 4 }],
      ['varfim', { action: 'ERROR', identifier: 4 }],
      ['PT_V', { action: 'SHIFT', identifier: 41 }],
      ['ID', { action: 'ERROR', identifier: 4 }],
      ['VIR', { action: 'ERROR', identifier: 14 }],
      ['inteiro', { action: 'ERROR', identifier: 4 }],
      ['real', { action: 'ERROR', identifier: 4 }],
      ['literal', { action: 'ERROR', identifier: 4 }],
      ['leia', { action: 'ERROR', identifier: 4 }],
      ['escreva', { action: 'ERROR', identifier: 4 }],
      ['LIT', { action: 'ERROR', identifier: 4 }],
      ['NUM', { action: 'ERROR', identifier: 4 }],
      ['ATR', { action: 'ERROR', identifier: 4 }],
      ['OPA', { action: 'ERROR', identifier: 4 }],
      ['se', { action: 'ERROR', identifier: 4 }],
      ['AB_P', { action: 'ERROR', identifier: 4 }],
      ['FC_P', { action: 'ERROR', identifier: 4 }],
      ['entao', { action: 'ERROR', identifier: 4 }],
      ['OPR', { action: 'ERROR', identifier: 4 }],
      ['fimse', { action: 'ERROR', identifier: 4 }],
      ['fim', { action: 'ERROR', identifier: 4 }],
      ['EOF', { action: 'ERROR', identifier: 4 }]
    ])
  ],
  [
    26,
    new Map<TypeofToken | ReservedWords, Action>([
      ['inicio', { action: 'ERROR', identifier: 4 }],
      ['varinicio', { action: 'ERROR', identifier: 4 }],
      ['varfim', { action: 'ERROR', identifier: 4 }],
      ['PT_V', { action: 'SHIFT', identifier: 42 }],
      ['ID', { action: 'ERROR', identifier: 4 }],
      ['VIR', { action: 'ERROR', identifier: 15 }],
      ['inteiro', { action: 'ERROR', identifier: 4 }],
      ['real', { action: 'ERROR', identifier: 4 }],
      ['literal', { action: 'ERROR', identifier: 4 }],
      ['leia', { action: 'ERROR', identifier: 4 }],
      ['escreva', { action: 'ERROR', identifier: 4 }],
      ['LIT', { action: 'ERROR', identifier: 4 }],
      ['NUM', { action: 'ERROR', identifier: 4 }],
      ['ATR', { action: 'ERROR', identifier: 4 }],
      ['OPA', { action: 'ERROR', identifier: 4 }],
      ['se', { action: 'ERROR', identifier: 4 }],
      ['AB_P', { action: 'ERROR', identifier: 4 }],
      ['FC_P', { action: 'ERROR', identifier: 4 }],
      ['entao', { action: 'ERROR', identifier: 4 }],
      ['OPR', { action: 'ERROR', identifier: 4 }],
      ['fimse', { action: 'ERROR', identifier: 4 }],
      ['fim', { action: 'ERROR', identifier: 4 }],
      ['EOF', { action: 'ERROR', identifier: 4 }]
    ])
  ],
  [
    27,
    new Map<TypeofToken | ReservedWords, Action>([
      ['inicio', { action: 'ERROR', identifier: 9 }],
      ['varinicio', { action: 'ERROR', identifier: 9 }],
      ['varfim', { action: 'ERROR', identifier: 9 }],
      ['PT_V', { action: 'REDUCE', identifier: 14 }],
      ['ID', { action: 'ERROR', identifier: 9 }],
      ['VIR', { action: 'ERROR', identifier: 18 }],
      ['inteiro', { action: 'ERROR', identifier: 9 }],
      ['real', { action: 'ERROR', identifier: 9 }],
      ['literal', { action: 'ERROR', identifier: 9 }],
      ['leia', { action: 'ERROR', identifier: 9 }],
      ['escreva', { action: 'ERROR', identifier: 9 }],
      ['LIT', { action: 'ERROR', identifier: 9 }],
      ['NUM', { action: 'ERROR', identifier: 9 }],
      ['ATR', { action: 'ERROR', identifier: 9 }],
      ['OPA', { action: 'ERROR', identifier: 9 }],
      ['se', { action: 'ERROR', identifier: 9 }],
      ['AB_P', { action: 'ERROR', identifier: 9 }],
      ['FC_P', { action: 'ERROR', identifier: 9 }],
      ['entao', { action: 'ERROR', identifier: 9 }],
      ['OPR', { action: 'ERROR', identifier: 9 }],
      ['fimse', { action: 'ERROR', identifier: 9 }],
      ['fim', { action: 'ERROR', identifier: 9 }],
      ['EOF', { action: 'ERROR', identifier: 9 }]
    ])
  ],
  [
    28,
    new Map<TypeofToken | ReservedWords, Action>([
      ['inicio', { action: 'ERROR', identifier: 9 }],
      ['varinicio', { action: 'ERROR', identifier: 9 }],
      ['varfim', { action: 'ERROR', identifier: 9 }],
      ['PT_V', { action: 'REDUCE', identifier: 15 }],
      ['ID', { action: 'ERROR', identifier: 9 }],
      ['VIR', { action: 'ERROR', identifier: 19 }],
      ['inteiro', { action: 'ERROR', identifier: 9 }],
      ['real', { action: 'ERROR', identifier: 9 }],
      ['literal', { action: 'ERROR', identifier: 9 }],
      ['leia', { action: 'ERROR', identifier: 9 }],
      ['escreva', { action: 'ERROR', identifier: 9 }],
      ['LIT', { action: 'ERROR', identifier: 9 }],
      ['NUM', { action: 'ERROR', identifier: 9 }],
      ['ATR', { action: 'ERROR', identifier: 9 }],
      ['OPA', { action: 'ERROR', identifier: 9 }],
      ['se', { action: 'ERROR', identifier: 9 }],
      ['AB_P', { action: 'ERROR', identifier: 9 }],
      ['FC_P', { action: 'ERROR', identifier: 9 }],
      ['entao', { action: 'ERROR', identifier: 9 }],
      ['OPR', { action: 'ERROR', identifier: 9 }],
      ['fimse', { action: 'ERROR', identifier: 9 }],
      ['fim', { action: 'ERROR', identifier: 9 }],
      ['EOF', { action: 'ERROR', identifier: 9 }]
    ])
  ],
  [
    29,
    new Map<TypeofToken | ReservedWords, Action>([
      ['inicio', { action: 'ERROR', identifier: 9 }],
      ['varinicio', { action: 'ERROR', identifier: 9 }],
      ['varfim', { action: 'ERROR', identifier: 9 }],
      ['PT_V', { action: 'REDUCE', identifier: 16 }],
      ['ID', { action: 'ERROR', identifier: 9 }],
      ['VIR', { action: 'ERROR', identifier: 20 }],
      ['inteiro', { action: 'ERROR', identifier: 9 }],
      ['real', { action: 'ERROR', identifier: 9 }],
      ['literal', { action: 'ERROR', identifier: 9 }],
      ['leia', { action: 'ERROR', identifier: 9 }],
      ['escreva', { action: 'ERROR', identifier: 9 }],
      ['LIT', { action: 'ERROR', identifier: 9 }],
      ['NUM', { action: 'ERROR', identifier: 9 }],
      ['ATR', { action: 'ERROR', identifier: 9 }],
      ['OPA', { action: 'ERROR', identifier: 9 }],
      ['se', { action: 'ERROR', identifier: 9 }],
      ['AB_P', { action: 'ERROR', identifier: 9 }],
      ['FC_P', { action: 'ERROR', identifier: 9 }],
      ['entao', { action: 'ERROR', identifier: 9 }],
      ['OPR', { action: 'ERROR', identifier: 9 }],
      ['fimse', { action: 'ERROR', identifier: 9 }],
      ['fim', { action: 'ERROR', identifier: 9 }],
      ['EOF', { action: 'ERROR', identifier: 9 }]
    ])
  ],
  [
    30,
    new Map<TypeofToken | ReservedWords, Action>([
      ['inicio', { action: 'ERROR', identifier: 4 }],
      ['varinicio', { action: 'ERROR', identifier: 4 }],
      ['varfim', { action: 'ERROR', identifier: 4 }],
      ['PT_V', { action: 'ERROR', identifier: 4 }],
      ['ID', { action: 'SHIFT', identifier: 45 }],
      ['VIR', { action: 'ERROR', identifier: 4 }],
      ['inteiro', { action: 'ERROR', identifier: 4 }],
      ['real', { action: 'ERROR', identifier: 4 }],
      ['literal', { action: 'ERROR', identifier: 4 }],
      ['leia', { action: 'ERROR', identifier: 4 }],
      ['escreva', { action: 'ERROR', identifier: 4 }],
      ['LIT', { action: 'ERROR', identifier: 4 }],
      ['NUM', { action: 'SHIFT', identifier: 46 }],
      ['ATR', { action: 'ERROR', identifier: 4 }],
      ['OPA', { action: 'ERROR', identifier: 4 }],
      ['se', { action: 'ERROR', identifier: 4 }],
      ['AB_P', { action: 'ERROR', identifier: 4 }],
      ['FC_P', { action: 'ERROR', identifier: 4 }],
      ['entao', { action: 'ERROR', identifier: 4 }],
      ['OPR', { action: 'ERROR', identifier: 4 }],
      ['fimse', { action: 'ERROR', identifier: 4 }],
      ['fim', { action: 'ERROR', identifier: 4 }],
      ['EOF', { action: 'ERROR', identifier: 4 }]
    ])
  ],
  [
    31,
    new Map<TypeofToken | ReservedWords, Action>([
      ['inicio', { action: 'ERROR', identifier: 9 }],
      ['varinicio', { action: 'ERROR', identifier: 9 }],
      ['varfim', { action: 'ERROR', identifier: 9 }],
      ['PT_V', { action: 'ERROR', identifier: 9 }],
      ['ID', { action: 'REDUCE', identifier: 24 }],
      ['VIR', { action: 'ERROR', identifier: 9 }],
      ['inteiro', { action: 'ERROR', identifier: 9 }],
      ['real', { action: 'ERROR', identifier: 9 }],
      ['literal', { action: 'ERROR', identifier: 9 }],
      ['leia', { action: 'REDUCE', identifier: 24 }],
      ['escreva', { action: 'REDUCE', identifier: 24 }],
      ['LIT', { action: 'ERROR', identifier: 9 }],
      ['NUM', { action: 'ERROR', identifier: 9 }],
      ['ATR', { action: 'ERROR', identifier: 9 }],
      ['OPA', { action: 'ERROR', identifier: 9 }],
      ['se', { action: 'REDUCE', identifier: 24 }],
      ['AB_P', { action: 'ERROR', identifier: 9 }],
      ['FC_P', { action: 'ERROR', identifier: 9 }],
      ['entao', { action: 'ERROR', identifier: 9 }],
      ['OPR', { action: 'ERROR', identifier: 9 }],
      ['fimse', { action: 'REDUCE', identifier: 24 }],
      ['fim', { action: 'REDUCE', identifier: 24 }],
      ['EOF', { action: 'ERROR', identifier: 9 }]
    ])
  ],
  [
    32,
    new Map<TypeofToken | ReservedWords, Action>([
      ['inicio', { action: 'ERROR', identifier: 4 }],
      ['varinicio', { action: 'ERROR', identifier: 4 }],
      ['varfim', { action: 'ERROR', identifier: 4 }],
      ['PT_V', { action: 'ERROR', identifier: 4 }],
      ['ID', { action: 'SHIFT', identifier: 12 }],
      ['VIR', { action: 'ERROR', identifier: 4 }],
      ['inteiro', { action: 'ERROR', identifier: 4 }],
      ['real', { action: 'ERROR', identifier: 4 }],
      ['literal', { action: 'ERROR', identifier: 4 }],
      ['leia', { action: 'SHIFT', identifier: 10 }],
      ['escreva', { action: 'SHIFT', identifier: 11 }],
      ['LIT', { action: 'ERROR', identifier: 4 }],
      ['NUM', { action: 'ERROR', identifier: 4 }],
      ['ATR', { action: 'ERROR', identifier: 4 }],
      ['OPA', { action: 'ERROR', identifier: 4 }],
      ['se', { action: 'SHIFT', identifier: 14 }],
      ['AB_P', { action: 'ERROR', identifier: 4 }],
      ['FC_P', { action: 'ERROR', identifier: 4 }],
      ['entao', { action: 'ERROR', identifier: 4 }],
      ['OPR', { action: 'ERROR', identifier: 4 }],
      ['fimse', { action: 'SHIFT', identifier: 35 }],
      ['fim', { action: 'ERROR', identifier: 4 }],
      ['EOF', { action: 'ERROR', identifier: 4 }]
    ])
  ],
  [
    33,
    new Map<TypeofToken | ReservedWords, Action>([
      ['inicio', { action: 'ERROR', identifier: 4 }],
      ['varinicio', { action: 'ERROR', identifier: 4 }],
      ['varfim', { action: 'ERROR', identifier: 4 }],
      ['PT_V', { action: 'ERROR', identifier: 4 }],
      ['ID', { action: 'SHIFT', identifier: 12 }],
      ['VIR', { action: 'ERROR', identifier: 4 }],
      ['inteiro', { action: 'ERROR', identifier: 4 }],
      ['real', { action: 'ERROR', identifier: 4 }],
      ['literal', { action: 'ERROR', identifier: 4 }],
      ['leia', { action: 'SHIFT', identifier: 10 }],
      ['escreva', { action: 'SHIFT', identifier: 11 }],
      ['LIT', { action: 'ERROR', identifier: 4 }],
      ['NUM', { action: 'ERROR', identifier: 4 }],
      ['ATR', { action: 'ERROR', identifier: 4 }],
      ['OPA', { action: 'ERROR', identifier: 4 }],
      ['se', { action: 'SHIFT', identifier: 14 }],
      ['AB_P', { action: 'ERROR', identifier: 4 }],
      ['FC_P', { action: 'ERROR', identifier: 4 }],
      ['entao', { action: 'ERROR', identifier: 4 }],
      ['OPR', { action: 'ERROR', identifier: 4 }],
      ['fimse', { action: 'SHIFT', identifier: 35 }],
      ['fim', { action: 'ERROR', identifier: 4 }],
      ['EOF', { action: 'ERROR', identifier: 4 }]
    ])
  ],
  [
    34,
    new Map<TypeofToken | ReservedWords, Action>([
      ['inicio', { action: 'ERROR', identifier: 4 }],
      ['varinicio', { action: 'ERROR', identifier: 4 }],
      ['varfim', { action: 'ERROR', identifier: 4 }],
      ['PT_V', { action: 'ERROR', identifier: 4 }],
      ['ID', { action: 'SHIFT', identifier: 12 }],
      ['VIR', { action: 'ERROR', identifier: 4 }],
      ['inteiro', { action: 'ERROR', identifier: 4 }],
      ['real', { action: 'ERROR', identifier: 4 }],
      ['literal', { action: 'ERROR', identifier: 4 }],
      ['leia', { action: 'SHIFT', identifier: 10 }],
      ['escreva', { action: 'SHIFT', identifier: 11 }],
      ['LIT', { action: 'ERROR', identifier: 4 }],
      ['NUM', { action: 'ERROR', identifier: 4 }],
      ['ATR', { action: 'ERROR', identifier: 4 }],
      ['OPA', { action: 'ERROR', identifier: 4 }],
      ['se', { action: 'SHIFT', identifier: 14 }],
      ['AB_P', { action: 'ERROR', identifier: 4 }],
      ['FC_P', { action: 'ERROR', identifier: 4 }],
      ['entao', { action: 'ERROR', identifier: 4 }],
      ['OPR', { action: 'ERROR', identifier: 4 }],
      ['fimse', { action: 'SHIFT', identifier: 35 }],
      ['fim', { action: 'ERROR', identifier: 4 }],
      ['EOF', { action: 'ERROR', identifier: 4 }]
    ])
  ],
  [
    35,
    new Map<TypeofToken | ReservedWords, Action>([
      ['inicio', { action: 'ERROR', identifier: 9 }],
      ['varinicio', { action: 'ERROR', identifier: 9 }],
      ['varfim', { action: 'ERROR', identifier: 9 }],
      ['PT_V', { action: 'ERROR', identifier: 9 }],
      ['ID', { action: 'REDUCE', identifier: 30 }],
      ['VIR', { action: 'ERROR', identifier: 9 }],
      ['inteiro', { action: 'ERROR', identifier: 9 }],
      ['real', { action: 'ERROR', identifier: 9 }],
      ['literal', { action: 'ERROR', identifier: 9 }],
      ['leia', { action: 'REDUCE', identifier: 30 }],
      ['escreva', { action: 'REDUCE', identifier: 30 }],
      ['LIT', { action: 'ERROR', identifier: 9 }],
      ['NUM', { action: 'ERROR', identifier: 9 }],
      ['ATR', { action: 'ERROR', identifier: 9 }],
      ['OPA', { action: 'ERROR', identifier: 9 }],
      ['se', { action: 'REDUCE', identifier: 30 }],
      ['AB_P', { action: 'ERROR', identifier: 9 }],
      ['FC_P', { action: 'ERROR', identifier: 9 }],
      ['entao', { action: 'ERROR', identifier: 9 }],
      ['OPR', { action: 'ERROR', identifier: 9 }],
      ['fimse', { action: 'REDUCE', identifier: 30 }],
      ['fim', { action: 'REDUCE', identifier: 30 }],
      ['EOF', { action: 'ERROR', identifier: 9 }]
    ])
  ],
  [
    36,
    new Map<TypeofToken | ReservedWords, Action>([
      ['inicio', { action: 'ERROR', identifier: 4 }],
      ['varinicio', { action: 'ERROR', identifier: 4 }],
      ['varfim', { action: 'ERROR', identifier: 4 }],
      ['PT_V', { action: 'ERROR', identifier: 4 }],
      ['ID', { action: 'SHIFT', identifier: 45 }],
      ['VIR', { action: 'ERROR', identifier: 4 }],
      ['inteiro', { action: 'ERROR', identifier: 4 }],
      ['real', { action: 'ERROR', identifier: 4 }],
      ['literal', { action: 'ERROR', identifier: 4 }],
      ['leia', { action: 'ERROR', identifier: 4 }],
      ['escreva', { action: 'ERROR', identifier: 4 }],
      ['LIT', { action: 'ERROR', identifier: 4 }],
      ['NUM', { action: 'SHIFT', identifier: 46 }],
      ['ATR', { action: 'ERROR', identifier: 4 }],
      ['OPA', { action: 'ERROR', identifier: 4 }],
      ['se', { action: 'ERROR', identifier: 4 }],
      ['AB_P', { action: 'ERROR', identifier: 4 }],
      ['FC_P', { action: 'ERROR', identifier: 4 }],
      ['entao', { action: 'ERROR', identifier: 4 }],
      ['OPR', { action: 'ERROR', identifier: 4 }],
      ['fimse', { action: 'ERROR', identifier: 4 }],
      ['fim', { action: 'ERROR', identifier: 4 }],
      ['EOF', { action: 'ERROR', identifier: 4 }]
    ])
  ],
  [
    37,
    new Map<TypeofToken | ReservedWords, Action>([
      ['inicio', { action: 'ERROR', identifier: 9 }],
      ['varinicio', { action: 'ERROR', identifier: 9 }],
      ['varfim', { action: 'ERROR', identifier: 9 }],
      ['PT_V', { action: 'ERROR', identifier: 9 }],
      ['ID', { action: 'REDUCE', identifier: 3 }],
      ['VIR', { action: 'ERROR', identifier: 9 }],
      ['inteiro', { action: 'ERROR', identifier: 9 }],
      ['real', { action: 'ERROR', identifier: 9 }],
      ['literal', { action: 'ERROR', identifier: 9 }],
      ['leia', { action: 'REDUCE', identifier: 3 }],
      ['escreva', { action: 'REDUCE', identifier: 3 }],
      ['LIT', { action: 'ERROR', identifier: 9 }],
      ['NUM', { action: 'ERROR', identifier: 9 }],
      ['ATR', { action: 'ERROR', identifier: 9 }],
      ['OPA', { action: 'ERROR', identifier: 9 }],
      ['se', { action: 'REDUCE', identifier: 3 }],
      ['AB_P', { action: 'ERROR', identifier: 9 }],
      ['FC_P', { action: 'ERROR', identifier: 9 }],
      ['entao', { action: 'ERROR', identifier: 9 }],
      ['OPR', { action: 'ERROR', identifier: 9 }],
      ['fimse', { action: 'ERROR', identifier: 9 }],
      ['fim', { action: 'REDUCE', identifier: 3 }],
      ['EOF', { action: 'ERROR', identifier: 9 }]
    ])
  ],
  [
    38,
    new Map<TypeofToken | ReservedWords, Action>([
      ['inicio', { action: 'ERROR', identifier: 9 }],
      ['varinicio', { action: 'ERROR', identifier: 9 }],
      ['varfim', { action: 'ERROR', identifier: 9 }],
      ['PT_V', { action: 'ERROR', identifier: 9 }],
      ['ID', { action: 'REDUCE', identifier: 4 }],
      ['VIR', { action: 'ERROR', identifier: 9 }],
      ['inteiro', { action: 'ERROR', identifier: 9 }],
      ['real', { action: 'ERROR', identifier: 9 }],
      ['literal', { action: 'ERROR', identifier: 9 }],
      ['leia', { action: 'REDUCE', identifier: 4 }],
      ['escreva', { action: 'REDUCE', identifier: 4 }],
      ['LIT', { action: 'ERROR', identifier: 9 }],
      ['NUM', { action: 'ERROR', identifier: 9 }],
      ['ATR', { action: 'ERROR', identifier: 9 }],
      ['OPA', { action: 'ERROR', identifier: 9 }],
      ['se', { action: 'REDUCE', identifier: 4 }],
      ['AB_P', { action: 'ERROR', identifier: 9 }],
      ['FC_P', { action: 'ERROR', identifier: 9 }],
      ['entao', { action: 'ERROR', identifier: 9 }],
      ['OPR', { action: 'ERROR', identifier: 9 }],
      ['fimse', { action: 'ERROR', identifier: 9 }],
      ['fim', { action: 'REDUCE', identifier: 4 }],
      ['EOF', { action: 'ERROR', identifier: 9 }]
    ])
  ],
  [
    39,
    new Map<TypeofToken | ReservedWords, Action>([
      ['inicio', { action: 'ERROR', identifier: 4 }],
      ['varinicio', { action: 'ERROR', identifier: 4 }],
      ['varfim', { action: 'ERROR', identifier: 4 }],
      ['PT_V', { action: 'SHIFT', identifier: 52 }],
      ['ID', { action: 'ERROR', identifier: 4 }],
      ['VIR', { action: 'ERROR', identifier: 16 }],
      ['inteiro', { action: 'ERROR', identifier: 4 }],
      ['real', { action: 'ERROR', identifier: 4 }],
      ['literal', { action: 'ERROR', identifier: 4 }],
      ['leia', { action: 'ERROR', identifier: 4 }],
      ['escreva', { action: 'ERROR', identifier: 4 }],
      ['LIT', { action: 'ERROR', identifier: 4 }],
      ['NUM', { action: 'ERROR', identifier: 4 }],
      ['ATR', { action: 'ERROR', identifier: 4 }],
      ['OPA', { action: 'ERROR', identifier: 4 }],
      ['se', { action: 'ERROR', identifier: 4 }],
      ['AB_P', { action: 'ERROR', identifier: 4 }],
      ['FC_P', { action: 'ERROR', identifier: 4 }],
      ['entao', { action: 'ERROR', identifier: 4 }],
      ['OPR', { action: 'ERROR', identifier: 4 }],
      ['fimse', { action: 'ERROR', identifier: 4 }],
      ['fim', { action: 'ERROR', identifier: 4 }],
      ['EOF', { action: 'ERROR', identifier: 4 }]
    ])
  ],
  [
    40,
    new Map<TypeofToken | ReservedWords, Action>([
      ['inicio', { action: 'ERROR', identifier: 9 }],
      ['varinicio', { action: 'ERROR', identifier: 9 }],
      ['varfim', { action: 'ERROR', identifier: 9 }],
      ['PT_V', { action: 'REDUCE', identifier: 7 }],
      ['ID', { action: 'ERROR', identifier: 9 }],
      ['VIR', { action: 'SHIFT', identifier: 53 }],
      ['inteiro', { action: 'ERROR', identifier: 9 }],
      ['real', { action: 'ERROR', identifier: 9 }],
      ['literal', { action: 'ERROR', identifier: 9 }],
      ['leia', { action: 'ERROR', identifier: 9 }],
      ['escreva', { action: 'ERROR', identifier: 9 }],
      ['LIT', { action: 'ERROR', identifier: 9 }],
      ['NUM', { action: 'ERROR', identifier: 9 }],
      ['ATR', { action: 'ERROR', identifier: 9 }],
      ['OPA', { action: 'ERROR', identifier: 9 }],
      ['se', { action: 'ERROR', identifier: 9 }],
      ['AB_P', { action: 'ERROR', identifier: 9 }],
      ['FC_P', { action: 'ERROR', identifier: 9 }],
      ['entao', { action: 'ERROR', identifier: 9 }],
      ['OPR', { action: 'ERROR', identifier: 9 }],
      ['fimse', { action: 'ERROR', identifier: 9 }],
      ['fim', { action: 'ERROR', identifier: 9 }],
      ['EOF', { action: 'ERROR', identifier: 9 }]
    ])
  ],
  [
    41,
    new Map<TypeofToken | ReservedWords, Action>([
      ['inicio', { action: 'ERROR', identifier: 9 }],
      ['varinicio', { action: 'ERROR', identifier: 9 }],
      ['varfim', { action: 'ERROR', identifier: 9 }],
      ['PT_V', { action: 'ERROR', identifier: 9 }],
      ['ID', { action: 'REDUCE', identifier: 12 }],
      ['VIR', { action: 'ERROR', identifier: 9 }],
      ['inteiro', { action: 'ERROR', identifier: 9 }],
      ['real', { action: 'ERROR', identifier: 9 }],
      ['literal', { action: 'ERROR', identifier: 9 }],
      ['leia', { action: 'REDUCE', identifier: 12 }],
      ['escreva', { action: 'REDUCE', identifier: 12 }],
      ['LIT', { action: 'ERROR', identifier: 9 }],
      ['NUM', { action: 'ERROR', identifier: 9 }],
      ['ATR', { action: 'ERROR', identifier: 9 }],
      ['OPA', { action: 'ERROR', identifier: 9 }],
      ['se', { action: 'REDUCE', identifier: 12 }],
      ['AB_P', { action: 'ERROR', identifier: 9 }],
      ['FC_P', { action: 'ERROR', identifier: 9 }],
      ['entao', { action: 'ERROR', identifier: 9 }],
      ['OPR', { action: 'ERROR', identifier: 9 }],
      ['fimse', { action: 'REDUCE', identifier: 12 }],
      ['fim', { action: 'REDUCE', identifier: 12 }],
      ['EOF', { action: 'ERROR', identifier: 9 }]
    ])
  ],
  [
    42,
    new Map<TypeofToken | ReservedWords, Action>([
      ['inicio', { action: 'ERROR', identifier: 9 }],
      ['varinicio', { action: 'ERROR', identifier: 9 }],
      ['varfim', { action: 'ERROR', identifier: 9 }],
      ['PT_V', { action: 'ERROR', identifier: 9 }],
      ['ID', { action: 'REDUCE', identifier: 13 }],
      ['VIR', { action: 'ERROR', identifier: 9 }],
      ['inteiro', { action: 'ERROR', identifier: 9 }],
      ['real', { action: 'ERROR', identifier: 9 }],
      ['literal', { action: 'ERROR', identifier: 9 }],
      ['leia', { action: 'REDUCE', identifier: 13 }],
      ['escreva', { action: 'REDUCE', identifier: 13 }],
      ['LIT', { action: 'ERROR', identifier: 9 }],
      ['NUM', { action: 'ERROR', identifier: 9 }],
      ['ATR', { action: 'ERROR', identifier: 9 }],
      ['OPA', { action: 'ERROR', identifier: 9 }],
      ['se', { action: 'REDUCE', identifier: 13 }],
      ['AB_P', { action: 'ERROR', identifier: 9 }],
      ['FC_P', { action: 'ERROR', identifier: 9 }],
      ['entao', { action: 'ERROR', identifier: 9 }],
      ['OPR', { action: 'ERROR', identifier: 9 }],
      ['fimse', { action: 'REDUCE', identifier: 13 }],
      ['fim', { action: 'REDUCE', identifier: 13 }],
      ['EOF', { action: 'ERROR', identifier: 9 }]
    ])
  ],
  [
    43,
    new Map<TypeofToken | ReservedWords, Action>([
      ['inicio', { action: 'ERROR', identifier: 4 }],
      ['varinicio', { action: 'ERROR', identifier: 4 }],
      ['varfim', { action: 'ERROR', identifier: 4 }],
      ['PT_V', { action: 'SHIFT', identifier: 54 }],
      ['ID', { action: 'ERROR', identifier: 4 }],
      ['VIR', { action: 'ERROR', identifier: 17 }],
      ['inteiro', { action: 'ERROR', identifier: 4 }],
      ['real', { action: 'ERROR', identifier: 4 }],
      ['literal', { action: 'ERROR', identifier: 4 }],
      ['leia', { action: 'ERROR', identifier: 4 }],
      ['escreva', { action: 'ERROR', identifier: 4 }],
      ['LIT', { action: 'ERROR', identifier: 4 }],
      ['NUM', { action: 'ERROR', identifier: 4 }],
      ['ATR', { action: 'ERROR', identifier: 4 }],
      ['OPA', { action: 'ERROR', identifier: 4 }],
      ['se', { action: 'ERROR', identifier: 4 }],
      ['AB_P', { action: 'ERROR', identifier: 4 }],
      ['FC_P', { action: 'ERROR', identifier: 4 }],
      ['entao', { action: 'ERROR', identifier: 4 }],
      ['OPR', { action: 'ERROR', identifier: 4 }],
      ['fimse', { action: 'ERROR', identifier: 4 }],
      ['fim', { action: 'ERROR', identifier: 4 }],
      ['EOF', { action: 'ERROR', identifier: 4 }]
    ])
  ],
  [
    44,
    new Map<TypeofToken | ReservedWords, Action>([
      ['inicio', { action: 'ERROR', identifier: 9 }],
      ['varinicio', { action: 'ERROR', identifier: 9 }],
      ['varfim', { action: 'ERROR', identifier: 9 }],
      ['PT_V', { action: 'REDUCE', identifier: 20 }],
      ['ID', { action: 'ERROR', identifier: 9 }],
      ['VIR', { action: 'ERROR', identifier: 25 }],
      ['inteiro', { action: 'ERROR', identifier: 9 }],
      ['real', { action: 'ERROR', identifier: 9 }],
      ['literal', { action: 'ERROR', identifier: 9 }],
      ['leia', { action: 'ERROR', identifier: 9 }],
      ['escreva', { action: 'ERROR', identifier: 9 }],
      ['LIT', { action: 'ERROR', identifier: 9 }],
      ['NUM', { action: 'ERROR', identifier: 9 }],
      ['ATR', { action: 'ERROR', identifier: 9 }],
      ['OPA', { action: 'SHIFT', identifier: 55 }],
      ['se', { action: 'ERROR', identifier: 9 }],
      ['AB_P', { action: 'ERROR', identifier: 9 }],
      ['FC_P', { action: 'ERROR', identifier: 9 }],
      ['entao', { action: 'ERROR', identifier: 9 }],
      ['OPR', { action: 'ERROR', identifier: 9 }],
      ['fimse', { action: 'ERROR', identifier: 9 }],
      ['fim', { action: 'ERROR', identifier: 9 }],
      ['EOF', { action: 'ERROR', identifier: 9 }]
    ])
  ],
  [
    45,
    new Map<TypeofToken | ReservedWords, Action>([
      ['inicio', { action: 'ERROR', identifier: 9 }],
      ['varinicio', { action: 'ERROR', identifier: 9 }],
      ['varfim', { action: 'ERROR', identifier: 9 }],
      ['PT_V', { action: 'REDUCE', identifier: 21 }],
      ['ID', { action: 'ERROR', identifier: 9 }],
      ['VIR', { action: 'ERROR', identifier: 22 }],
      ['inteiro', { action: 'ERROR', identifier: 9 }],
      ['real', { action: 'ERROR', identifier: 9 }],
      ['literal', { action: 'ERROR', identifier: 9 }],
      ['leia', { action: 'ERROR', identifier: 9 }],
      ['escreva', { action: 'ERROR', identifier: 9 }],
      ['LIT', { action: 'ERROR', identifier: 9 }],
      ['NUM', { action: 'ERROR', identifier: 9 }],
      ['ATR', { action: 'ERROR', identifier: 9 }],
      ['OPA', { action: 'REDUCE', identifier: 21 }],
      ['se', { action: 'ERROR', identifier: 9 }],
      ['AB_P', { action: 'ERROR', identifier: 9 }],
      ['FC_P', { action: 'REDUCE', identifier: 21 }],
      ['entao', { action: 'ERROR', identifier: 9 }],
      ['OPR', { action: 'REDUCE', identifier: 21 }],
      ['fimse', { action: 'ERROR', identifier: 9 }],
      ['fim', { action: 'ERROR', identifier: 9 }],
      ['EOF', { action: 'ERROR', identifier: 9 }]
    ])
  ],
  [
    46,
    new Map<TypeofToken | ReservedWords, Action>([
      ['inicio', { action: 'ERROR', identifier: 9 }],
      ['varinicio', { action: 'ERROR', identifier: 9 }],
      ['varfim', { action: 'ERROR', identifier: 9 }],
      ['PT_V', { action: 'REDUCE', identifier: 22 }],
      ['ID', { action: 'ERROR', identifier: 9 }],
      ['VIR', { action: 'ERROR', identifier: 23 }],
      ['inteiro', { action: 'ERROR', identifier: 9 }],
      ['real', { action: 'ERROR', identifier: 9 }],
      ['literal', { action: 'ERROR', identifier: 9 }],
      ['leia', { action: 'ERROR', identifier: 9 }],
      ['escreva', { action: 'ERROR', identifier: 9 }],
      ['LIT', { action: 'ERROR', identifier: 9 }],
      ['NUM', { action: 'ERROR', identifier: 9 }],
      ['ATR', { action: 'ERROR', identifier: 9 }],
      ['OPA', { action: 'REDUCE', identifier: 22 }],
      ['se', { action: 'ERROR', identifier: 9 }],
      ['AB_P', { action: 'ERROR', identifier: 9 }],
      ['FC_P', { action: 'REDUCE', identifier: 22 }],
      ['entao', { action: 'ERROR', identifier: 9 }],
      ['OPR', { action: 'REDUCE', identifier: 22 }],
      ['fimse', { action: 'ERROR', identifier: 9 }],
      ['fim', { action: 'ERROR', identifier: 9 }],
      ['EOF', { action: 'ERROR', identifier: 9 }]
    ])
  ],
  [
    47,
    new Map<TypeofToken | ReservedWords, Action>([
      ['inicio', { action: 'ERROR', identifier: 9 }],
      ['varinicio', { action: 'ERROR', identifier: 9 }],
      ['varfim', { action: 'ERROR', identifier: 9 }],
      ['PT_V', { action: 'ERROR', identifier: 9 }],
      ['ID', { action: 'REDUCE', identifier: 27 }],
      ['VIR', { action: 'ERROR', identifier: 9 }],
      ['inteiro', { action: 'ERROR', identifier: 9 }],
      ['real', { action: 'ERROR', identifier: 9 }],
      ['literal', { action: 'ERROR', identifier: 9 }],
      ['leia', { action: 'REDUCE', identifier: 27 }],
      ['escreva', { action: 'REDUCE', identifier: 27 }],
      ['LIT', { action: 'ERROR', identifier: 9 }],
      ['NUM', { action: 'ERROR', identifier: 9 }],
      ['ATR', { action: 'ERROR', identifier: 9 }],
      ['OPA', { action: 'ERROR', identifier: 9 }],
      ['se', { action: 'REDUCE', identifier: 27 }],
      ['AB_P', { action: 'ERROR', identifier: 9 }],
      ['FC_P', { action: 'ERROR', identifier: 9 }],
      ['entao', { action: 'ERROR', identifier: 9 }],
      ['OPR', { action: 'ERROR', identifier: 9 }],
      ['fimse', { action: 'REDUCE', identifier: 27 }],
      ['fim', { action: 'REDUCE', identifier: 27 }],
      ['EOF', { action: 'ERROR', identifier: 9 }]
    ])
  ],
  [
    48,
    new Map<TypeofToken | ReservedWords, Action>([
      ['inicio', { action: 'ERROR', identifier: 9 }],
      ['varinicio', { action: 'ERROR', identifier: 9 }],
      ['varfim', { action: 'ERROR', identifier: 9 }],
      ['PT_V', { action: 'ERROR', identifier: 9 }],
      ['ID', { action: 'REDUCE', identifier: 28 }],
      ['VIR', { action: 'ERROR', identifier: 9 }],
      ['inteiro', { action: 'ERROR', identifier: 9 }],
      ['real', { action: 'ERROR', identifier: 9 }],
      ['literal', { action: 'ERROR', identifier: 9 }],
      ['leia', { action: 'REDUCE', identifier: 28 }],
      ['escreva', { action: 'REDUCE', identifier: 28 }],
      ['LIT', { action: 'ERROR', identifier: 9 }],
      ['NUM', { action: 'ERROR', identifier: 9 }],
      ['ATR', { action: 'ERROR', identifier: 9 }],
      ['OPA', { action: 'ERROR', identifier: 9 }],
      ['se', { action: 'REDUCE', identifier: 28 }],
      ['AB_P', { action: 'ERROR', identifier: 9 }],
      ['FC_P', { action: 'ERROR', identifier: 9 }],
      ['entao', { action: 'ERROR', identifier: 9 }],
      ['OPR', { action: 'ERROR', identifier: 9 }],
      ['fimse', { action: 'REDUCE', identifier: 28 }],
      ['fim', { action: 'REDUCE', identifier: 28 }],
      ['EOF', { action: 'ERROR', identifier: 9 }]
    ])
  ],
  [
    49,
    new Map<TypeofToken | ReservedWords, Action>([
      ['inicio', { action: 'ERROR', identifier: 9 }],
      ['varinicio', { action: 'ERROR', identifier: 9 }],
      ['varfim', { action: 'ERROR', identifier: 9 }],
      ['PT_V', { action: 'ERROR', identifier: 9 }],
      ['ID', { action: 'REDUCE', identifier: 29 }],
      ['VIR', { action: 'ERROR', identifier: 9 }],
      ['inteiro', { action: 'ERROR', identifier: 9 }],
      ['real', { action: 'ERROR', identifier: 9 }],
      ['literal', { action: 'ERROR', identifier: 9 }],
      ['leia', { action: 'REDUCE', identifier: 29 }],
      ['escreva', { action: 'REDUCE', identifier: 29 }],
      ['LIT', { action: 'ERROR', identifier: 9 }],
      ['NUM', { action: 'ERROR', identifier: 9 }],
      ['ATR', { action: 'ERROR', identifier: 9 }],
      ['OPA', { action: 'ERROR', identifier: 9 }],
      ['se', { action: 'REDUCE', identifier: 29 }],
      ['AB_P', { action: 'ERROR', identifier: 9 }],
      ['FC_P', { action: 'ERROR', identifier: 9 }],
      ['entao', { action: 'ERROR', identifier: 9 }],
      ['OPR', { action: 'ERROR', identifier: 9 }],
      ['fimse', { action: 'REDUCE', identifier: 29 }],
      ['fim', { action: 'REDUCE', identifier: 29 }],
      ['EOF', { action: 'ERROR', identifier: 9 }]
    ])
  ],
  [
    50,
    new Map<TypeofToken | ReservedWords, Action>([
      ['inicio', { action: 'ERROR', identifier: 4 }],
      ['varinicio', { action: 'ERROR', identifier: 4 }],
      ['varfim', { action: 'ERROR', identifier: 4 }],
      ['PT_V', { action: 'ERROR', identifier: 4 }],
      ['ID', { action: 'ERROR', identifier: 10 }],
      ['VIR', { action: 'ERROR', identifier: 4 }],
      ['inteiro', { action: 'ERROR', identifier: 4 }],
      ['real', { action: 'ERROR', identifier: 4 }],
      ['literal', { action: 'ERROR', identifier: 4 }],
      ['leia', { action: 'ERROR', identifier: 4 }],
      ['escreva', { action: 'ERROR', identifier: 4 }],
      ['LIT', { action: 'ERROR', identifier: 4 }],
      ['NUM', { action: 'ERROR', identifier: 4 }],
      ['ATR', { action: 'ERROR', identifier: 4 }],
      ['OPA', { action: 'ERROR', identifier: 4 }],
      ['se', { action: 'ERROR', identifier: 4 }],
      ['AB_P', { action: 'ERROR', identifier: 4 }],
      ['FC_P', { action: 'SHIFT', identifier: 56 }],
      ['entao', { action: 'ERROR', identifier: 10 }],
      ['OPR', { action: 'ERROR', identifier: 4 }],
      ['fimse', { action: 'ERROR', identifier: 4 }],
      ['fim', { action: 'ERROR', identifier: 4 }],
      ['EOF', { action: 'ERROR', identifier: 4 }]
    ])
  ],
  [
    51,
    new Map<TypeofToken | ReservedWords, Action>([
      ['inicio', { action: 'ERROR', identifier: 11 }],
      ['varinicio', { action: 'ERROR', identifier: 11 }],
      ['varfim', { action: 'ERROR', identifier: 11 }],
      ['PT_V', { action: 'ERROR', identifier: 11 }],
      ['ID', { action: 'ERROR', identifier: 11 }],
      ['VIR', { action: 'ERROR', identifier: 11 }],
      ['inteiro', { action: 'ERROR', identifier: 11 }],
      ['real', { action: 'ERROR', identifier: 11 }],
      ['literal', { action: 'ERROR', identifier: 11 }],
      ['leia', { action: 'ERROR', identifier: 11 }],
      ['escreva', { action: 'ERROR', identifier: 11 }],
      ['LIT', { action: 'ERROR', identifier: 11 }],
      ['NUM', { action: 'ERROR', identifier: 11 }],
      ['ATR', { action: 'ERROR', identifier: 11 }],
      ['OPA', { action: 'ERROR', identifier: 11 }],
      ['se', { action: 'ERROR', identifier: 11 }],
      ['AB_P', { action: 'ERROR', identifier: 11 }],
      ['FC_P', { action: 'ERROR', identifier: 11 }],
      ['entao', { action: 'ERROR', identifier: 11 }],
      ['OPR', { action: 'SHIFT', identifier: 57 }],
      ['fimse', { action: 'ERROR', identifier: 11 }],
      ['fim', { action: 'ERROR', identifier: 11 }],
      ['EOF', { action: 'ERROR', identifier: 11 }]
    ])
  ],
  [
    52,
    new Map<TypeofToken | ReservedWords, Action>([
      ['inicio', { action: 'ERROR', identifier: 9 }],
      ['varinicio', { action: 'ERROR', identifier: 9 }],
      ['varfim', { action: 'REDUCE', identifier: 5 }],
      ['PT_V', { action: 'ERROR', identifier: 9 }],
      ['ID', { action: 'ERROR', identifier: 9 }],
      ['VIR', { action: 'ERROR', identifier: 9 }],
      ['inteiro', { action: 'REDUCE', identifier: 5 }],
      ['real', { action: 'REDUCE', identifier: 5 }],
      ['literal', { action: 'REDUCE', identifier: 5 }],
      ['leia', { action: 'ERROR', identifier: 9 }],
      ['escreva', { action: 'ERROR', identifier: 9 }],
      ['LIT', { action: 'ERROR', identifier: 9 }],
      ['NUM', { action: 'ERROR', identifier: 9 }],
      ['ATR', { action: 'ERROR', identifier: 9 }],
      ['OPA', { action: 'ERROR', identifier: 9 }],
      ['se', { action: 'ERROR', identifier: 9 }],
      ['AB_P', { action: 'ERROR', identifier: 9 }],
      ['FC_P', { action: 'ERROR', identifier: 9 }],
      ['entao', { action: 'ERROR', identifier: 9 }],
      ['OPR', { action: 'ERROR', identifier: 9 }],
      ['fimse', { action: 'ERROR', identifier: 9 }],
      ['fim', { action: 'ERROR', identifier: 9 }],
      ['EOF', { action: 'ERROR', identifier: 9 }]
    ])
  ],
  [
    53,
    new Map<TypeofToken | ReservedWords, Action>([
      ['inicio', { action: 'ERROR', identifier: 4 }],
      ['varinicio', { action: 'ERROR', identifier: 4 }],
      ['varfim', { action: 'ERROR', identifier: 21 }],
      ['PT_V', { action: 'ERROR', identifier: 4 }],
      ['ID', { action: 'SHIFT', identifier: 40 }],
      ['VIR', { action: 'ERROR', identifier: 4 }],
      ['inteiro', { action: 'ERROR', identifier: 21 }],
      ['real', { action: 'ERROR', identifier: 21 }],
      ['literal', { action: 'ERROR', identifier: 21 }],
      ['leia', { action: 'ERROR', identifier: 4 }],
      ['escreva', { action: 'ERROR', identifier: 4 }],
      ['LIT', { action: 'ERROR', identifier: 4 }],
      ['NUM', { action: 'ERROR', identifier: 4 }],
      ['ATR', { action: 'ERROR', identifier: 4 }],
      ['OPA', { action: 'ERROR', identifier: 4 }],
      ['se', { action: 'ERROR', identifier: 4 }],
      ['AB_P', { action: 'ERROR', identifier: 4 }],
      ['FC_P', { action: 'ERROR', identifier: 4 }],
      ['entao', { action: 'ERROR', identifier: 4 }],
      ['OPR', { action: 'ERROR', identifier: 4 }],
      ['fimse', { action: 'ERROR', identifier: 4 }],
      ['fim', { action: 'ERROR', identifier: 4 }],
      ['EOF', { action: 'ERROR', identifier: 4 }]
    ])
  ],
  [
    54,
    new Map<TypeofToken | ReservedWords, Action>([
      ['inicio', { action: 'ERROR', identifier: 9 }],
      ['varinicio', { action: 'ERROR', identifier: 9 }],
      ['varfim', { action: 'ERROR', identifier: 9 }],
      ['PT_V', { action: 'ERROR', identifier: 9 }],
      ['ID', { action: 'REDUCE', identifier: 18 }],
      ['VIR', { action: 'ERROR', identifier: 9 }],
      ['inteiro', { action: 'ERROR', identifier: 9 }],
      ['real', { action: 'ERROR', identifier: 9 }],
      ['literal', { action: 'ERROR', identifier: 9 }],
      ['leia', { action: 'REDUCE', identifier: 18 }],
      ['escreva', { action: 'REDUCE', identifier: 18 }],
      ['LIT', { action: 'ERROR', identifier: 9 }],
      ['NUM', { action: 'ERROR', identifier: 9 }],
      ['ATR', { action: 'ERROR', identifier: 9 }],
      ['OPA', { action: 'ERROR', identifier: 9 }],
      ['se', { action: 'REDUCE', identifier: 18 }],
      ['AB_P', { action: 'ERROR', identifier: 9 }],
      ['FC_P', { action: 'ERROR', identifier: 9 }],
      ['entao', { action: 'ERROR', identifier: 9 }],
      ['OPR', { action: 'ERROR', identifier: 9 }],
      ['fimse', { action: 'REDUCE', identifier: 18 }],
      ['fim', { action: 'REDUCE', identifier: 18 }],
      ['EOF', { action: 'ERROR', identifier: 9 }]
    ])
  ],
  [
    55,
    new Map<TypeofToken | ReservedWords, Action>([
      ['inicio', { action: 'ERROR', identifier: 4 }],
      ['varinicio', { action: 'ERROR', identifier: 4 }],
      ['varfim', { action: 'ERROR', identifier: 4 }],
      ['PT_V', { action: 'ERROR', identifier: 4 }],
      ['ID', { action: 'SHIFT', identifier: 45 }],
      ['VIR', { action: 'ERROR', identifier: 4 }],
      ['inteiro', { action: 'ERROR', identifier: 4 }],
      ['real', { action: 'ERROR', identifier: 4 }],
      ['literal', { action: 'ERROR', identifier: 4 }],
      ['leia', { action: 'ERROR', identifier: 4 }],
      ['escreva', { action: 'ERROR', identifier: 4 }],
      ['LIT', { action: 'ERROR', identifier: 4 }],
      ['NUM', { action: 'SHIFT', identifier: 46 }],
      ['ATR', { action: 'ERROR', identifier: 4 }],
      ['OPA', { action: 'ERROR', identifier: 4 }],
      ['se', { action: 'ERROR', identifier: 4 }],
      ['AB_P', { action: 'ERROR', identifier: 4 }],
      ['FC_P', { action: 'ERROR', identifier: 4 }],
      ['entao', { action: 'ERROR', identifier: 4 }],
      ['OPR', { action: 'ERROR', identifier: 4 }],
      ['fimse', { action: 'ERROR', identifier: 4 }],
      ['fim', { action: 'ERROR', identifier: 4 }],
      ['EOF', { action: 'ERROR', identifier: 4 }]
    ])
  ],
  [
    56,
    new Map<TypeofToken | ReservedWords, Action>([
      ['inicio', { action: 'ERROR', identifier: 12 }],
      ['varinicio', { action: 'ERROR', identifier: 12 }],
      ['varfim', { action: 'ERROR', identifier: 12 }],
      ['PT_V', { action: 'ERROR', identifier: 12 }],
      ['ID', { action: 'ERROR', identifier: 13 }],
      ['VIR', { action: 'ERROR', identifier: 12 }],
      ['inteiro', { action: 'ERROR', identifier: 12 }],
      ['real', { action: 'ERROR', identifier: 12 }],
      ['literal', { action: 'ERROR', identifier: 12 }],
      ['leia', { action: 'ERROR', identifier: 12 }],
      ['escreva', { action: 'ERROR', identifier: 12 }],
      ['LIT', { action: 'ERROR', identifier: 12 }],
      ['NUM', { action: 'ERROR', identifier: 12 }],
      ['ATR', { action: 'ERROR', identifier: 12 }],
      ['OPA', { action: 'ERROR', identifier: 12 }],
      ['se', { action: 'ERROR', identifier: 12 }],
      ['AB_P', { action: 'ERROR', identifier: 12 }],
      ['FC_P', { action: 'ERROR', identifier: 12 }],
      ['entao', { action: 'SHIFT', identifier: 60 }],
      ['OPR', { action: 'ERROR', identifier: 12 }],
      ['fimse', { action: 'ERROR', identifier: 12 }],
      ['fim', { action: 'ERROR', identifier: 12 }],
      ['EOF', { action: 'ERROR', identifier: 12 }]
    ])
  ],
  [
    57,
    new Map<TypeofToken | ReservedWords, Action>([
      ['inicio', { action: 'ERROR', identifier: 4 }],
      ['varinicio', { action: 'ERROR', identifier: 4 }],
      ['varfim', { action: 'ERROR', identifier: 4 }],
      ['PT_V', { action: 'ERROR', identifier: 4 }],
      ['ID', { action: 'SHIFT', identifier: 45 }],
      ['VIR', { action: 'ERROR', identifier: 4 }],
      ['inteiro', { action: 'ERROR', identifier: 4 }],
      ['real', { action: 'ERROR', identifier: 4 }],
      ['literal', { action: 'ERROR', identifier: 4 }],
      ['leia', { action: 'ERROR', identifier: 4 }],
      ['escreva', { action: 'ERROR', identifier: 4 }],
      ['LIT', { action: 'ERROR', identifier: 4 }],
      ['NUM', { action: 'SHIFT', identifier: 46 }],
      ['ATR', { action: 'ERROR', identifier: 4 }],
      ['OPA', { action: 'ERROR', identifier: 4 }],
      ['se', { action: 'ERROR', identifier: 4 }],
      ['AB_P', { action: 'ERROR', identifier: 4 }],
      ['FC_P', { action: 'ERROR', identifier: 4 }],
      ['entao', { action: 'ERROR', identifier: 4 }],
      ['OPR', { action: 'ERROR', identifier: 4 }],
      ['fimse', { action: 'ERROR', identifier: 4 }],
      ['fim', { action: 'ERROR', identifier: 4 }],
      ['EOF', { action: 'ERROR', identifier: 4 }]
    ])
  ],
  [
    58,
    new Map<TypeofToken | ReservedWords, Action>([
      ['inicio', { action: 'ERROR', identifier: 9 }],
      ['varinicio', { action: 'ERROR', identifier: 9 }],
      ['varfim', { action: 'ERROR', identifier: 9 }],
      ['PT_V', { action: 'REDUCE', identifier: 6 }],
      ['ID', { action: 'ERROR', identifier: 9 }],
      ['VIR', { action: 'ERROR', identifier: 9 }],
      ['inteiro', { action: 'ERROR', identifier: 9 }],
      ['real', { action: 'ERROR', identifier: 9 }],
      ['literal', { action: 'ERROR', identifier: 9 }],
      ['leia', { action: 'ERROR', identifier: 9 }],
      ['escreva', { action: 'ERROR', identifier: 9 }],
      ['LIT', { action: 'ERROR', identifier: 9 }],
      ['NUM', { action: 'ERROR', identifier: 9 }],
      ['ATR', { action: 'ERROR', identifier: 9 }],
      ['OPA', { action: 'ERROR', identifier: 9 }],
      ['se', { action: 'ERROR', identifier: 9 }],
      ['AB_P', { action: 'ERROR', identifier: 9 }],
      ['FC_P', { action: 'ERROR', identifier: 9 }],
      ['entao', { action: 'ERROR', identifier: 9 }],
      ['OPR', { action: 'ERROR', identifier: 9 }],
      ['fimse', { action: 'ERROR', identifier: 9 }],
      ['fim', { action: 'ERROR', identifier: 9 }],
      ['EOF', { action: 'ERROR', identifier: 9 }]
    ])
  ],
  [
    59,
    new Map<TypeofToken | ReservedWords, Action>([
      ['inicio', { action: 'ERROR', identifier: 9 }],
      ['varinicio', { action: 'ERROR', identifier: 9 }],
      ['varfim', { action: 'ERROR', identifier: 9 }],
      ['PT_V', { action: 'REDUCE', identifier: 19 }],
      ['ID', { action: 'ERROR', identifier: 9 }],
      ['VIR', { action: 'ERROR', identifier: 24 }],
      ['inteiro', { action: 'ERROR', identifier: 9 }],
      ['real', { action: 'ERROR', identifier: 9 }],
      ['literal', { action: 'ERROR', identifier: 9 }],
      ['leia', { action: 'ERROR', identifier: 9 }],
      ['escreva', { action: 'ERROR', identifier: 9 }],
      ['LIT', { action: 'ERROR', identifier: 9 }],
      ['NUM', { action: 'ERROR', identifier: 9 }],
      ['ATR', { action: 'ERROR', identifier: 9 }],
      ['OPA', { action: 'ERROR', identifier: 9 }],
      ['se', { action: 'ERROR', identifier: 9 }],
      ['AB_P', { action: 'ERROR', identifier: 9 }],
      ['FC_P', { action: 'ERROR', identifier: 9 }],
      ['entao', { action: 'ERROR', identifier: 9 }],
      ['OPR', { action: 'ERROR', identifier: 9 }],
      ['fimse', { action: 'ERROR', identifier: 9 }],
      ['fim', { action: 'ERROR', identifier: 9 }],
      ['EOF', { action: 'ERROR', identifier: 9 }]
    ])
  ],
  [
    60,
    new Map<TypeofToken | ReservedWords, Action>([
      ['inicio', { action: 'ERROR', identifier: 9 }],
      ['varinicio', { action: 'ERROR', identifier: 9 }],
      ['varfim', { action: 'ERROR', identifier: 9 }],
      ['PT_V', { action: 'ERROR', identifier: 9 }],
      ['ID', { action: 'REDUCE', identifier: 25 }],
      ['VIR', { action: 'ERROR', identifier: 9 }],
      ['inteiro', { action: 'ERROR', identifier: 9 }],
      ['real', { action: 'ERROR', identifier: 9 }],
      ['literal', { action: 'ERROR', identifier: 9 }],
      ['leia', { action: 'REDUCE', identifier: 25 }],
      ['escreva', { action: 'REDUCE', identifier: 25 }],
      ['LIT', { action: 'ERROR', identifier: 9 }],
      ['NUM', { action: 'ERROR', identifier: 9 }],
      ['ATR', { action: 'ERROR', identifier: 9 }],
      ['OPA', { action: 'ERROR', identifier: 9 }],
      ['se', { action: 'REDUCE', identifier: 25 }],
      ['AB_P', { action: 'ERROR', identifier: 9 }],
      ['FC_P', { action: 'ERROR', identifier: 9 }],
      ['entao', { action: 'ERROR', identifier: 9 }],
      ['OPR', { action: 'ERROR', identifier: 9 }],
      ['fimse', { action: 'REDUCE', identifier: 25 }],
      ['fim', { action: 'ERROR', identifier: 9 }],
      ['EOF', { action: 'ERROR', identifier: 9 }]
    ])
  ],
  [
    61,
    new Map<TypeofToken | ReservedWords, Action>([
      ['inicio', { action: 'ERROR', identifier: 9 }],
      ['varinicio', { action: 'ERROR', identifier: 9 }],
      ['varfim', { action: 'ERROR', identifier: 9 }],
      ['PT_V', { action: 'ERROR', identifier: 9 }],
      ['ID', { action: 'ERROR', identifier: 9 }],
      ['VIR', { action: 'ERROR', identifier: 9 }],
      ['inteiro', { action: 'ERROR', identifier: 9 }],
      ['real', { action: 'ERROR', identifier: 9 }],
      ['literal', { action: 'ERROR', identifier: 9 }],
      ['leia', { action: 'ERROR', identifier: 9 }],
      ['escreva', { action: 'ERROR', identifier: 9 }],
      ['LIT', { action: 'ERROR', identifier: 9 }],
      ['NUM', { action: 'ERROR', identifier: 9 }],
      ['ATR', { action: 'ERROR', identifier: 9 }],
      ['OPA', { action: 'ERROR', identifier: 9 }],
      ['se', { action: 'ERROR', identifier: 9 }],
      ['AB_P', { action: 'ERROR', identifier: 9 }],
      ['FC_P', { action: 'REDUCE', identifier: 26 }],
      ['entao', { action: 'ERROR', identifier: 9 }],
      ['OPR', { action: 'ERROR', identifier: 9 }],
      ['fimse', { action: 'ERROR', identifier: 9 }],
      ['fim', { action: 'ERROR', identifier: 9 }],
      ['EOF', { action: 'ERROR', identifier: 9 }]
    ])
  ]
])

const GOTO_TABLE: GotoTable = new Map([
  [0, new Map<NonTerminals, number>([['P', 1]])],
  [2, new Map<NonTerminals, number>([['V', 3]])],
  [
    3,
    new Map<NonTerminals, number>([
      ['A', 5],
      ['ES', 6],
      ['CMD', 7],
      ['COND', 8],
      ['CAB', 13]
    ])
  ],
  [
    4,
    new Map<NonTerminals, number>([
      ['LV', 15],
      ['D', 16],
      ['TIPO', 18]
    ])
  ],
  [
    6,
    new Map<NonTerminals, number>([
      ['A', 22],
      ['ES', 6],
      ['CMD', 7],
      ['COND', 8],
      ['CAB', 13]
    ])
  ],
  [
    7,
    new Map<NonTerminals, number>([
      ['A', 23],
      ['ES', 6],
      ['CMD', 7],
      ['COND', 8],
      ['CAB', 13]
    ])
  ],
  [
    8,
    new Map<NonTerminals, number>([
      ['A', 24],
      ['ES', 6],
      ['CMD', 7],
      ['COND', 8],
      ['CAB', 13]
    ])
  ],
  [11, new Map<NonTerminals, number>([['ARG', 26]])],
  [
    13,
    new Map<NonTerminals, number>([
      ['ES', 32],
      ['CMD', 33],
      ['COND', 34],
      ['CAB', 13],
      ['CP', 31]
    ])
  ],
  [
    16,
    new Map<NonTerminals, number>([
      ['LV', 37],
      ['D', 16],
      ['TIPO', 18]
    ])
  ],
  [18, new Map<NonTerminals, number>([['L', 39]])],
  [
    30,
    new Map<NonTerminals, number>([
      ['LD', 43],
      ['OPRD', 44]
    ])
  ],
  [
    32,
    new Map<NonTerminals, number>([
      ['ES', 32],
      ['CMD', 33],
      ['COND', 34],
      ['CAB', 13],
      ['CP', 47]
    ])
  ],
  [
    33,
    new Map<NonTerminals, number>([
      ['ES', 32],
      ['CMD', 33],
      ['COND', 34],
      ['CAB', 13],
      ['CP', 48]
    ])
  ],
  [
    34,
    new Map<NonTerminals, number>([
      ['ES', 32],
      ['CMD', 33],
      ['COND', 34],
      ['CAB', 13],
      ['CP', 49]
    ])
  ],
  [
    36,
    new Map<NonTerminals, number>([
      ['OPRD', 51],
      ['EXP_R', 50]
    ])
  ],
  [53, new Map<NonTerminals, number>([['L', 58]])],
  [55, new Map<NonTerminals, number>([['OPRD', 59]])],
  [57, new Map<NonTerminals, number>([['OPRD', 61]])]
])

const FOLLOW_TABLE: FollowTable = new Map([
  ["P'", new Map<TypeofToken | ReservedWords, null>([['EOF', null]])],
  ['P', new Map<TypeofToken | ReservedWords, null>([['EOF', null]])],
  [
    'V',
    new Map<TypeofToken | ReservedWords, null>([
      ['fim', null],
      ['leia', null],
      ['escreva', null],
      ['ID', null],
      ['se', null]
    ])
  ],
  [
    'LV',
    new Map<TypeofToken | ReservedWords, null>([
      ['fim', null],
      ['leia', null],
      ['escreva', null],
      ['ID', null],
      ['se', null]
    ])
  ],
  [
    'D',
    new Map<TypeofToken | ReservedWords, null>([
      ['varfim', null],
      ['inteiro', null],
      ['real', null],
      ['literal', null]
    ])
  ],
  ['L', new Map<TypeofToken | ReservedWords, null>([['PT_V', null]])],
  ['TIPO', new Map<TypeofToken | ReservedWords, null>([['ID', null]])],
  ['A', new Map<TypeofToken | ReservedWords, null>([['EOF', null]])],
  [
    'ES',
    new Map<TypeofToken | ReservedWords, null>([
      ['fim', null],
      ['leia', null],
      ['escreva', null],
      ['ID', null],
      ['se', null],
      ['fimse', null]
    ])
  ],
  ['ARG', new Map<TypeofToken | ReservedWords, null>([['PT_V', null]])],
  [
    'CMD',
    new Map<TypeofToken | ReservedWords, null>([
      ['fim', null],
      ['leia', null],
      ['escreva', null],
      ['ID', null],
      ['se', null],
      ['fimse', null]
    ])
  ],
  ['LD', new Map<TypeofToken | ReservedWords, null>([['PT_V', null]])],
  [
    'OPRD',
    new Map<TypeofToken | ReservedWords, null>([
      ['OPA', null],
      ['PT_V', null],
      ['OPR', null],
      ['FC_P', null]
    ])
  ],
  [
    'COND',
    new Map<TypeofToken | ReservedWords, null>([
      ['fim', null],
      ['leia', null],
      ['escreva', null],
      ['ID', null],
      ['se', null],
      ['fimse', null]
    ])
  ],
  [
    'CAB',
    new Map<TypeofToken | ReservedWords, null>([
      ['leia', null],
      ['escreva', null],
      ['ID', null],
      ['se', null],
      ['fimse', null]
    ])
  ],
  ['EXP_R', new Map<TypeofToken | ReservedWords, null>([['FC_P', null]])],
  [
    'CP',
    new Map<TypeofToken | ReservedWords, null>([
      ['fim', null],
      ['leia', null],
      ['escreva', null],
      ['ID', null],
      ['se', null],
      ['fimse', null]
    ])
  ]
])

const GRAMMAR_RULES = new Map([
  [0, "P'->P"],
  [1, 'P->inicio V A'],
  [2, 'V->varinicio LV'],
  [3, 'LV->D LV'],
  [4, 'LV->varfim pt_v'],
  [5, 'D->TIPO L pt_v'],
  [6, 'L->id vir L'],
  [7, 'L->id'],
  [8, 'TIPO->inteiro'],
  [9, 'TIPO->real'],
  [10, 'TIPO->literal'],
  [11, 'A->ES A'],
  [12, 'ES->leia id pt_v'],
  [13, 'ES->escreva ARG pt_v'],
  [14, 'ARG->lit'],
  [15, 'ARG->num'],
  [16, 'ARG->id'],
  [17, 'A->CMD A'],
  [18, 'CMD->id atr LD pt_v'],
  [19, 'LD->OPRD opa OPRD'],
  [20, 'LD->OPRD'],
  [21, 'OPRD->id'],
  [22, 'OPRD->num'],
  [23, 'A->COND A'],
  [24, 'COND->CAB CP'],
  [25, 'CAB->se ab_p EXP_R fc_p entao'],
  [26, 'EXP_R->OPRD opr OPRD'],
  [27, 'CP->ES CP'],
  [28, 'CP->CMD CP'],
  [29, 'CP->COND CP'],
  [30, 'CP->fimse'],
  [31, 'A->fim']
])

const POP_AMOUNT_PER_RULE = new Map(
  Array.from(GRAMMAR_RULES.entries()).map((value) => [
    value[0],
    value[1].replace(/[A-Z']+->/, '').split(' ').length
  ])
)

const RULE_LETTER = new Map(
  Array.from(GRAMMAR_RULES.entries()).map((value) => [
    value[0],
    value[1].replace(/->.*/, '')
  ])
)

const EXPECTED_TOKENS_PER_STATE: Map<State, Array<string>> = new Map([
  [0, ['inicio']],
  [1, ['EOF']],
  [2, ['varinicio']],
  [3, ['identificador', 'leia', 'escreva', 'se', 'fim']],
  [4, ['varfim', 'inteiro', 'real', 'literal']],
  [5, ['EOF']],
  [6, ['identificador', 'leia', 'escreva', 'se', 'fim']],
  [7, ['identificador', 'leia', 'escreva', 'se', 'fim']],
  [8, ['identificador', 'leia', 'escreva', 'se', 'fim']],
  [9, ['EOF']],
  [10, ['identificador']],
  [11, ['identificador', 'constante literal', 'constante numérica']],
  [12, ['<-']],
  [13, ['identificador', 'leia', 'escreva', 'se', 'fimse']],
  [14, ['(']],
  [15, ['identificador', 'leia', 'escreva', 'se', 'fim']],
  [16, ['varfim', 'inteiro', 'real', 'literal']],
  [17, [';']],
  [18, ['identificador']],
  [19, ['identificador']],
  [20, ['identificador']],
  [21, ['identificador']],
  [22, ['EOF']],
  [23, ['EOF']],
  [24, ['EOF']],
  [25, [';']],
  [26, [';']],
  [27, [';']],
  [28, [';']],
  [29, [';']],
  [30, ['identificador', 'constante numérica']],
  [31, ['identificador', 'leia', 'escreva', 'se', 'fimse', 'fim']],
  [32, ['identificador', 'leia', 'escreva', 'se', 'fimse']],
  [33, ['identificador', 'leia', 'escreva', 'se', 'fimse']],
  [34, ['identificador', 'leia', 'escreva', 'se', 'fimse']],
  [35, ['identificador', 'leia', 'escreva', 'se', 'fimse', 'fim']],
  [36, ['identificador', 'constante numérica']],
  [37, ['identificador', 'leia', 'escreva', 'se', 'fim']],
  [38, ['identificador', 'leia', 'escreva', 'se', 'fim']],
  [39, [';']],
  [40, [';', ',']],
  [41, ['identificador', 'leia', 'escreva', 'se', 'fimse', 'fim']],
  [42, ['identificador', 'leia', 'escreva', 'se', 'fimse', 'fim']],
  [43, [';']],
  [44, [';', '+', '-', '*', '/']],
  [45, [';', '+', '-', '*', '/', ')', '<', '>', '<=', '>=', '=', '<>']],
  [46, [';', '+', '-', '*', '/', ')', '<', '>', '<=', '>=', '=', '<>']],
  [47, ['identificador', 'leia', 'escreva', 'se', 'fimse', 'fim']],
  [48, ['identificador', 'leia', 'escreva', 'se', 'fimse', 'fim']],
  [49, ['identificador', 'leia', 'escreva', 'se', 'fimse', 'fim']],
  [50, [')']],
  [51, ['<', '>', '<=', '>=', '=', '<>']],
  [52, ['varfim', 'inteiro', 'real', 'literal']],
  [53, ['identificador']],
  [54, ['identificador', 'leia', 'escreva', 'se', 'fimse', 'fim']],
  [55, ['identificador', 'constante numérica']],
  [56, ['entao']],
  [57, ['identificador', 'constante numérica']],
  [58, [';']],
  [59, [';']],
  [60, ['identificador', 'leia', 'escreva', 'se', 'fimse']],
  [61, [')']]
])

export {
  ACTION_TABLE,
  GOTO_TABLE,
  FOLLOW_TABLE,
  GRAMMAR_RULES,
  POP_AMOUNT_PER_RULE,
  RULE_LETTER,
  EXPECTED_TOKENS_PER_STATE
}
